apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: grafana
  namespace: monitoring
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://grafana.github.io/helm-charts
      chart: grafana
      version: 8.6.3
      sourceRef:
        kind: HelmRepository
        name: grafana-charts
        namespace: flux-system
      interval: 5m
  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 7
  values:
    persistence:
      enabled: true
      storageClassName: longhorn
      size: 1Gi
    useStatefulSet: true
    imageRenderer:
      enabled: true
    env:
      GF_FEATURE_TOGGLES_ENABLE: publicDashboards
    envFromSecret: grafana-secret
    smtp:
      existingSecret: "grafana-secret"
      userKey: "user"
      passwordKey: "password"
    grafana.ini:
      server:
        domain: grafana.${DOMAIN}
        root_url: https://%(domain)s/
        read_timeout: 10m
      dataproxy:
        timeout: 600
      security:
        disable_initial_admin_creation: true
      auth:
        oauth_auto_login: true
        oauth_allow_insecure_email_lookup: true
      auth.generic_oauth:
        enabled: true
        client_id: grafana
        auth_url: https://auth.${DOMAIN}/api/oidc/authorization
        api_url: https://auth.${DOMAIN}/api/oidc/userinfo
        token_url: https://auth.${DOMAIN}/api/oidc/token
        name: Authelia
        icon: signin
        scopes: openid profile email groups
        empty_scopes: false
        login_attribute_path: preferred_username
        groups_attribute_path: groups
        name_attribute_path: name
        use_pkce: true
        allowed_groups: admins
      auth.generic_oauth.group_mapping:
        org_id: 1
        role_attribute_path: |
          contains(groups[*], 'admins') && 'Admin'
      auth.basic:
        enabled: false
      smtp:
        enabled: true
        host: mail.${DOMAIN}:587
        from_address: svc_grafana@${DOMAIN}
        ehlo_identity: "grafana.k3s.i.${DOMAIN}"
    dashboardProviders:
      dashboardproviders.yaml:
        apiVersion: 1
        providers:
        - name: 'default'
          orgId: 1
          folder: 'autoimported'
          type: file
          disableDeletion: false
          editable: true
          options:
            path: /var/lib/grafana/dashboards/default
    datasources:
      datasources.yaml:
        apiVersion: 1
        datasources:
        - name: Prometheus-Kube
          type: prometheus
          url: http://kube-prometheus-stack-prometheus:9090
          access: proxy
        - name: Prometheus-External
          type: prometheus
          url: http://prometheus-external:9090
          access: proxy
        - name: Loki
          isDefault: true
          type: loki
          access: proxy
          url: http://loki-loki-distributed-gateway
    plugins:
      - marcusolsson-json-datasource
      - speakyourcode-button-panel
    dashboards:
      default:
        # Ref: https://grafana.com/grafana/dashboards/12175
        calico-felix:
          gnetId: 12175
          revision: 5
          datasource: Prometheus-Kube
        # Ref: https://grafana.com/grafana/dashboards/13502
        minio:
          gnetId: 13502
          revision: 26
          datasource: Prometheus-External
        # Ref: https://grafana.com/grafana/dashboards/11315
        unifi-client-insights:
          gnetId: 11315
          revision: 9
          datasource: Prometheus-External
        # Ref: https://grafana.com/grafana/dashboards/11311
        unifi-network-sites:
          gnetId: 11311
          revision: 5
          datasource: Prometheus-External
        # Ref: https://grafana.com/grafana/dashboards/11314
        unifi-uap-insights:
          gnetId: 11314
          revision: 10
          datasource: Prometheus-External
        # Ref: https://grafana.com/grafana/dashboards/11312
        unifi-usw-insights:
          gnetId: 11312
          revision: 9
          datasource: Prometheus-External
        # Ref: https://grafana.com/grafana/dashboards/11313
        unifi-usg-insights:
          gnetId: 11313
          revision: 9
          datasource: Prometheus-External
        # Ref: https://grafana.com/grafana/dashboards/15549
        node-problem-detector:
          gnetId: 15549
          revision: 1
          datasource: Prometheus-Kube
        # Ref: https://grafana.com/grafana/dashboards/15549
        speedtest-exporter:
          gnetId: 13665
          revision: 4
          datasource: Prometheus-External
        # Ref: https://grafana.com/grafana/dashboards/13659
        blackbox-exporter:
          gnetId: 13659
          revision: 1
          datasource: Prometheus-External
        flux-cluster:
          url: https://raw.githubusercontent.com/fluxcd/flux2/main/manifests/monitoring/grafana/dashboards/cluster.json
          datasource: Prometheus-Kube
        flux-control-plane:
          url: https://raw.githubusercontent.com/fluxcd/flux2/main/manifests/monitoring/grafana/dashboards/control-plane.json
          datasource: Prometheus-Kube
        netdata:
          gnetId: 7107
          revision: 1
          datasource: Prometheus-External
    sidecar:
      dashboards:
        enabled: true
        searchNamespace: ALL
      datasources:
        enabled: true
        searchNamespace: ALL
    ingress:
      enabled: true
      ingressClassName: nginx
      annotations:
        cert-manager.io/issuer: freeipa-issuer
        cert-manager.io/issuer-group: certmanager.freeipa.org
        cert-manager.io/issuer-kind: ClusterIssuer
        cert-manager.io/common-name: grafana.k3s.i.${DOMAIN}
        nignx.ingress.kubernetes.io/force-ssl-redirect: "true"
      hosts:
      - "grafana.k3s.i.${DOMAIN}"
      tls:
      - secretName: grafana-tls
        hosts:
        - "grafana.k3s.i.${DOMAIN}"
