apiVersion: v1
kind: ConfigMap
metadata:
  namespace: monitoring
  name: grafana-litestream
data:
  litestream.yml: |
    dbs:
    - path: /var/lib/grafana/grafana.db
      replicas:
        - type: s3
          bucket: grafana
          path: grafana
          endpoint: https://s3.i.${DOMAIN}:9000
