apiVersion: v1
kind: Secret
metadata:
    name: grafana-smtp-secret
    namespace: monitoring
stringData:
    user: ENC[AES256_GCM,data:1do6ITtHsHx0szA3G3hfUvqKZ7CX,iv:xhVQ6h84mZJO0yr9vo5RN5taPuNMWzK5LHhr/UYwnrE=,tag:516xbr1bm3cS69aCEMyB+w==,type:str]
    password: ENC[AES256_GCM,data:fIB2IRmojtZ0QdaGuKeVacovzVS4HW5S449DvOg0yv/l7QqWdLILsXc7Sl6UmQi8fo1DYh3IWmvdaCNs9PVxPRiOMze2NufExUxvxdazsstY1CvrZhNh94RJ4DJ28NeBOPsGYw==,iv:DZAbT5PXq4ArHYP68I8qsYd/uTkoRBMF8r/0f4o3gow=,tag:FIVgDMy4TjDgk7eP03hxdA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2024-03-24T08:14:33Z"
    mac: ENC[AES256_GCM,data:QPwjbkxqWnakT9aw18pxHmYdcJeYNTNATRYgAqLlBIQCocNkp1fUvzjVybrhMNmTEYHczybdA+xqpn/GQe7puaiyx10pKSwqMSaf3cO+pMhqrPGh8BU7RJPlN+v9C1gXpCCbeHI9jmF7v1U0hcJqBHpbYmdOJzQoRayuo12G1JE=,iv:lShvygZ8mVsie4xlQp4IuUGN9nWlsMe6S6xHBDR9bRU=,tag:o0ndy0gHuHpGblQ7b/HHJg==,type:str]
    pgp:
        - created_at: "2024-03-24T08:14:33Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA70fE7dz6LU0AQ/9Gh3hJ5ndcaZ+usQsxbB3bd11KueDzzP1+sDEo+bktxUx
            yiI57gPohq3cYPNapZIGqm4fnSIwNaeHr8jYgi/PfZ24Q+etjhgrZUbkkq1gmCT4
            0I+cpqjTnFkbdtKP2LGJCqlf+zL85gfaXvLo4Wn3dejzqiulRPhLE+Ko5dlHFH69
            WaUcxpLuy+vHyezBU0rdd/o45x73+uPidn/lG+ll1daOUm4oa4gOsb5UjIt0QwwJ
            3Lr6b48ed0jlFgcEyDngIMoMrs1xtDiyI0Dhz/+3oLzlI0GF0rXpSf6cUKGF3Hgc
            4D+zw0nUp6+Up233i1OtKw9vIG9ryaceeNom/u19w/YJe8/6mWFPONIbB9mZ6Sa0
            IhElOnQJq5yZILUvgm3KcLnyi07a9TVyQLTwB7QcEbT1aIx/58lJqlcJHacGzZYq
            b+P0x1mK08GkrKg7EMb7me9nDddhZ64XpYYbBgYNyfs1qOX2s3wtJoMZj6tlPauh
            Om640PjoeR5Ca+N32PXtTXEE7TpYduRwVxgQxO/zP2BFwHUNhRqhdgRNSxhKgoq8
            vfh5aITsP8KTUlRggI53DmlUCQ+5BrPopyaFYOVXXViaiouHiObMQIUjVJBtdJv3
            u6dgeFIbRKEEbZwUKEoJ7RaBFpqaMeqE+yzGkNzC4kvX4p8Zyjxqf4fINH4YtdnS
            XgE5kGn23DLxijydjnU9UNlDP7BKzCf7A5HRGxeyfp6DbdaBLHmAVxevTho/x/2f
            WWYrbyPAxqUXttXSukhge8kG44/5RjaEd2buQvwoq3wgcSRvdJuAV+hBpb/FYN8=
            =sbxG
            -----END PGP MESSAGE-----
          fp: 1DF23F1E7AFCAB40F26B210123CFBB30193553AA
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
