---

#
# Below vars are for the xanmanning.k3s role
# ...see https://github.com/PyratLabs/ansible-role-k3s#globalcluster-variables
#

# Use a specific version of k3s
k3s_release_version: "v1.24.3+k3s1"

# Install using hard links rather than symbolic links.
# ...if you are using the system-upgrade-controller you will need to use hard links rather than symbolic links as the controller will not be able to follow symbolic links.
k3s_install_hard_links: true

# Escalate user privileges for all tasks.
k3s_become_for_all: true
k3s_become: true

# Enable debugging
k3s_debug: false

# HA settings
k3s_etcd_datastore: true
k3s_registration_address: 10.13.2.40 # equal to kubevip_address
k3s_registration_domain: k8s-api.i.stabl.one

k3s_server_manifests_templates:
- "calico/calico-installation.yaml.j2"
- "kube-vip/kube-vip-rbac.yaml.j2"
- "kube-vip/kube-vip-daemonset.yaml.j2"

# Custom manifest URLs
k3s_server_manifests_urls:
- url: https://docs.projectcalico.org/archive/v3.19/manifests/tigera-operator.yaml
  filename: tigera-operator.yaml

# Values for Kube-VIP
kube_vip_tag_version: v0.4.4
kubevip_interface: eth0

kubeconfig_local_path: ../cluster/kubeconfig.yml
