---
- hosts: all
  become: yes
  become_method: sudo
  roles:
    - ../roles/portainer
  vars:
    replica: true
    replica_container_name: replica
    docker_dir: /var/docker
    freeipa_dir: "{{docker_dir}}/replica"

  vars_files:
    - ../secrets.yml
  tasks:
    - name: get svc_mail uid
      shell: "id -u {{mailserver_bindUser}}"
      register: bindUserUID
      changed_when: False

    - name: get svc_mail gid
      shell: "id -g {{mailserver_bindUser}}"
      register: bindUserGID
      changed_when: False
#DOCKER
    - name: create docker network
      docker_network:
        name: primary
        ipam_config:
          - subnet: "172.18.0.0/16"
#REPLICA
    - name: get ip address for replica in primary network
      shell: "docker inspect -f {{ '{{' }}.NetworkSettings.Networks.primary.IPAddress{{ '}}' }} {{replica_container_name}}"
      register: replica_container_primary_ip
      become: yes
#POSTFIX

    - name: deploy postfix
      include:  postfix/postfix.yml
    - name: start acme.sh container
      docker_container:
        name: acme.sh
        image: neilpang/acme.sh
        state: started
        detach: true
        recreate: no
        restart_policy: always
        volumes:
          - "{{docker_dir}}/mail/ssl/:/acme.sh"
        command: daemon
        env:
          DYNV6_TOKEN: "{{mailserver_dynv6_token}}"
# REMOVE STAGING
    - name: wait for container to be ready
      shell: |
        until [ "`/usr/bin/docker inspect -f {{ '{{' }}.State.Running{{ '}}' }} acme.sh`"=="true" ]; do
          sleep 0.1;
        done;
    - name: get cert
      shell: |
        export DYNV6_TOKEN="{{mailserver_dynv6_token}}" && \
        docker exec acme.sh --issue -d mail.{{domain_name}} --dns dns_dynv6 \
        --cert-file      /acme.sh/cert.pem  \
        --key-file       /acme.sh/key.pem  \
        --fullchain-file /acme.sh/fullchain.pem
      register: result
      failed_when: result.rc == 1
      changed_when: result.rc == 0
# Dovecot
    - name: dovecot
      include: dovecot/dovecot.yml

    - name: include rspamd.yml
      include: rspamd/rspamd.yml
