apiVersion: v1
kind: Secret
metadata:
    name: jellyfin-exporter
    namespace: monitoring
data:
    token: ENC[AES256_GCM,data:TCwDyVkmI/bGO/JLfQETGs9ywnEI1KV7w/9nMgtukgY=,iv:2rFFZZ4+nubB8kQwsaAh73sc0tEg6qfrfEfEayxoj00=,tag:RW0KNu2nOfirGdCNSzzB7w==,type:str]
type: Opaque
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-12-18T21:47:05Z"
    mac: ENC[AES256_GCM,data:j4znqpQOWSe5hf3aVkkW2odOIUFAeY0gLhpb5vA60jJ7sQswPDI2A2pyulzQ+8qu/ewE74WDEvZj9t6E0wpkQjXL85qBOhH5lPaGg50rg7JtsOtxkqw2K4I+etYy0jhkbHaElFqXSevvneEvuFpFli6/9JalgvA4DSDONyIeSDw=,iv:0fBkQJuZ7QVjGYTNLe5Mveg2mffF4naCajP//CXMAN4=,tag:2lDhxa7fS+BmUFWwWGY82g==,type:str]
    pgp:
        - created_at: "2022-12-18T21:47:04Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA70fE7dz6LU0AQ/9Eo/3IObrH09bC4TAzqvX3ftuxQ45FS5tpgsElUqwzBsE
            IF7eOJXweqJIpHxGAFWgReKsj6NtmVfXdZ9gMjUEz39EJ1BgeJfiFMthsaruK3YQ
            0XK19uTL4vwOqppkx2Kc4KE/nMTof023P6Gm8/4cC/2Yjk2efuPYGypZdrzohaEl
            scz53YMLeZurjBRsH8guU4t6qrvJBauUl7pVjA8sAgAyapijcZ/pzA1NKTuqHC33
            FkZE+1JpWPiwi/9Wa4zQssvCrCT4qgGx11badtOpIxH3BedB2+SvT+nWCZ5CwecR
            FT1xUtR6U4AdBmPmDGqRxqDxKl7WUvYQJ5ZCOjYzwjd8P9q2ZKOLw3F39CDjl2KV
            tjsCmyoT+iU3lkDwp4fD5rDFXUvFLqP0NhJZqb0daBBKGmJv6Dlh8PJRcnMIws/L
            m9WsZkDY8Gf5OqqYSPcYNPPGa+/HUucOff3kwc0fO/Elt/xjcsnA5by89uCZHb3R
            3pq/ot4PS6malpjREPJMH/DSyg53Wsm9WxcWS8cD+UX/iNDQ8nNZKGHR05Va7HZp
            kZk1/BPGrf9ljDoGfLI38PfUFKmqqpWJfOjNF4gsi3YidzqvExEFsDsw+tuSVMhv
            MfqNtjvhAedUlVQzsthp+sgyi8yKHMyv+h3tWJB5cQoNk1oKCJ2mZl5bSugdGJjS
            XgF3zQToXkBQn0zyjfewHcmQHctDyrJVW7pmGmaAPp0waNan5Nb110rvMhcLPiR1
            pZr86PgqrqZHXpoelaZk+DZKso0xLh88tnHg00vZBkEIn1Vy9X8ZwkiRVL6fkNM=
            =kDk2
            -----END PGP MESSAGE-----
          fp: 1DF23F1E7AFCAB40F26B210123CFBB30193553AA
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
