apiVersion: v1
kind: Secret
metadata:
    name: loki-basic-auth
    namespace: monitoring
type: Opaque
stringData:
    #ENC[AES256_GCM,data:ng5/x9AOIEms83d8M97Zry1qjJwMTxobmhYX9W7iR2DEWaAg05CVC4p/Q1uTuUU0mrpZlH2oZyUQ7eaTTPHg9vxXuwOK91kJ5LALiK86Vg==,iv:taqQSYyf1iuCVFid4nJG6fwlXqF9P/bVwoF3owvFGr4=,tag:BC+zgbkWInEXJopasrvDUQ==,type:comment]
    #ENC[AES256_GCM,data:7W+KxUwpLpUU0AO0MXZf6mcULtUBA61mv9bgWJS82YZnI14SfU+sc6t2sXddzMMA0pV8vXHYgPfRo6u3dtR1neDm9PcJBp9uF091VqY=,iv:2ksE/b0cjj2qnOAQIcV93l045c3bLMDEMrrnXnPqHVo=,tag:/Vqi5mnweMYMLIiY0/ENNw==,type:comment]
    #ENC[AES256_GCM,data:BmWNjZPqdE5NdLBvj1BBrgp1+/nuMBvOIOIOdM8WPbWrMA==,iv:AQK3XBFCOKBO+/xsrRLQqWXhagGVzJD+IR92sbih91s=,tag:jFjTnPH3q1++Vo3nL1k8tg==,type:comment]
    #ENC[AES256_GCM,data:2P6zHJafhyiRFS4XW9sx/l85qFbzWwewq+Kr/HDSUqaiAg==,iv:91B2LSSu/Tp/lXPVcZ2GlS/Tx/8bDBf+8HzgVStpfbE=,tag:yx9TW5SG2fvBERmOS7YKPQ==,type:comment]
    #ENC[AES256_GCM,data:ZOSzp3O9zvGM+ck6n+fj/uM4DiexXE+Dgf1w0mARICK5McAOIBDiNOp+datHybasz4WURzrRnMFxep030aM=,iv:2VnAGJQ04qz8wBFfziUjJNibFsdnViI6inG9daEXyjU=,tag:Q12FXsy6gPmi2F2+HtoiZg==,type:comment]
    #ENC[AES256_GCM,data:xNlgWr7R/cuqMPsdClj11gBY9LvpsQfoHAwbcvpaBLFSGy9YpcDsVp7/Me9fQx9Hwp5iRSQY7b7oO3HpYZ+bBfSErtwCYwjRHyl0RQ==,iv:Q1gHSeFZTxjP3rECtW58NkVo97/d3hFIMOFvXWE1yYA=,tag:Qal3rZCHNNQyEzcS/soqGQ==,type:comment]
    .htpasswd: ENC[AES256_GCM,data:v+leGAOpDDspH+F7pXP5ddPWjMRXdZyrkQmNulLbw6F/Fh1OT69ofAWLPOM+kd9ZqPbcfaVdbfDBD8wfHtlVmNHMGQ5HqqZz1lIV7JawxFQIql6Fz6lmgYSR998/rxPIHWf3U3Lg1k6ojlN2zB2Z0Tzd+y4wTvI4ZbykYVRhdZ+NNmsFAsUtYjBDO0YbNCDZsG3PlYGbiqplLnCBWxdCjvmHg+xXghA3wNxqLB/WbfcnEFBZ1e5lmvjI6EfQnd9QtlFywHOrEUiTjQfEKgpxiU2PO5Gu/USGoebMJAjWON6hXtfI9XZeM9KvL7nFfG3leD/+ZV9voCqMdMMD0K5VDkOhyNehTNHhxNLBFNaxvsWZvIE+xeVLoVyaZmMfG9XgLQdBtIdh/H9GtUbLAHT6w8qG+uFwB+jV9Uf/Je+ZIExZi2cZqX6kg15PLe16gCb+lxMNQ//ECcedNHhoBlhhweUvAmZcna8ZE+KXHqUz0H4WwIS9YqZq8YDh1XGMqVgCOiLi7Nywd1kME8Rm+3a58hqAuU/4xBOHQLcopmzoPOXs2/XIitlRUPKGZqvchJtS3ao=,iv:F4LmahZRtgcpzFJFPD0vcEVYR2h7f2K0ZNGVFd76Fe0=,tag:JMXbLD/UzP3MVCuV4UKSbg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2026-08-08T13:19:33Z"
    mac: ENC[AES256_GCM,data:UnjF7B11IlM3lWrCBvx5n7dMPyvr5ycTpjzpL+NZyRGq7srEIcsfKchytKjYtoRXI6Xx6zKo0IvxMYSqrWlWouyoJAP7pr6cxI+0a3CUWY33Gt+A4q3yumKdsovSrWjtW53sD/S05Kzapq5ALUEWakyj3LmNv08QUsZbfqFdeHU=,iv:6dTJ5eVZoyt1SqN659TDd7cywhNIZcrDBksToHQxwb8=,tag:LahNY5EBvl9DBwDje72CYA==,type:str]
    pgp:
        - created_at: "2026-08-08T13:14:09Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA70fE7dz6LU0AQ/7BFxVki395EOOLRxiWUVWZHAfKWGulo5ocvuCAeRzLPyj
            6i1ty+WqR7ZuTwyGPRFuVmLdY3QYRT4OMTZomYvTWVq7bWnAyCN2c0kjhdHvo78B
            dmh/e26GsD3bkTKaJvo6We/fmEROFHYAXCFPGd55JbdlrWPEYsLZJ75yd1bTV3cW
            yaFlVrMs1Eh2gYzvUusT3aDomYsq3a8QKOkAFlMjkxA28lLrmOeiQvBnqXO+l6I2
            LH7hjiwHMvXgtuZPZPOArFemEfOp9KN1pDEpPBjtImwoYYt2e4e8obl5HAsyWFQH
            DJeNJ/sfqIP6SQYMNEWGyJ+KL8zQnfW2ZvheDyeC3IXXUkRNvBGRspQrEmOC4/ED
            X3f44XoVSVTQmd2ZJZJ/nN6cVW6g5GemjeW7FBxiP/UF5O3NIoT+9+Fh6BKYuq+u
            WHUTnaI3rRFoof84hYS7FOVV3onW/KHT2Yx6pwiwkjDUO/6f4Z8Mrj6pqvV7gZ6q
            ubbOvxrPOonaplqMxTp6FQC+FFsCzC1w+pvw9UYq+tJW+w9UEDnPED+DkS9tSM2C
            oId08xPz/Hz7eR+7wGBxrqlHSn4IARbrO6SsOK/7Yf9avXrws75UkuumCQ2gE0/Y
            KaH5Q/cQvT2C5D3EtG4QTP2f8/1yTjeZnFgkJRvkF02wqUje0N7lgTU2gZP/AoXS
            XgGzAxDb5C/9Gd8iwT/99j53ygCjdpyFukaUh90IjVCEVnFWYrPPIEz33/ln1g8o
            mVy0XKMuafTHTAnllrLBZF4LJhWM9Im+atJ7IdOps44wNV8xDOZT5yVTCMIQ/74=
            =hA6c
            -----END PGP MESSAGE-----
          fp: 1DF23F1E7AFCAB40F26B210123CFBB30193553AA
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
