- name: Template script
  become: true
  template:
    src: "nc_reports.sh"
    dest: "/etc/nc_reports.sh"
    owner: root
    mode: '0750'
  vars:
    syncoid_backup_mail_user: svc_grafana
    syncoid_backup_mail_user_password: "{{logging.grafana.bind_user.password}}"
- name: Copy systemd files
  become: true
  copy:
    src: "{{item}}"
    dest: /etc/systemd/system/
  with_items:
    - nc_reports.service
    - nc_reports.timer
- name: Start timer
  become: true
  systemd:
    name: nc_reports.timer
    state: started
