- name: make fonts directory
  file:
    path: "{{ lookup('env','HOME') }}/.local/share/fonts"
    state: directory
- name: download fonts
  get_url:
    url: "{{ item }}"
    dest: "{{ lookup('env','HOME') }}/.local/share/fonts/"
  with_items:
    - "https://github.com/romkatv/powerlevel10k-media/raw/master/MesloLGS%20NF%20Regular.ttf"
    - "https://github.com/romkatv/powerlevel10k-media/raw/master/MesloLGS%20NF%20Bold.ttf"
    - "https://github.com/romkatv/powerlevel10k-media/raw/master/MesloLGS%20NF%20Italic.ttf"
    - "https://github.com/romkatv/powerlevel10k-media/raw/master/MesloLGS%20NF%20Bold%20Italic.ttf"
- name: update fonts
  command: fc-cache -f -v
