apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: document-server
  namespace: default
  annotations:
    cert-manager.io/issuer: freeipa-issuer
    cert-manager.io/issuer-group: certmanager.freeipa.org
    cert-manager.io/issuer-kind: ClusterIssuer
    cert-manager.io/common-name: docsrv.k3s.i.${DOMAIN}
    nginx.ingress.kubernetes.io/configuration-snippet: |
      proxy_set_header X-Forwarded-Host docsrv.stabl.one;
      proxy_set_header X-Forwarded-Proto https;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    nginx.ingress.kubernetes.io/upstream-vhost: docsrv.stabl.one
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - docsrv.k3s.i.${DOMAIN}
    secretName: document-server-cert
  rules:
  - host: docsrv.k3s.i.${DOMAIN}
    http:
      paths:
        - path: "/"
          pathType: Prefix
          backend:
            service:
              name: document-server
              port:
                number: 80
