apiVersion: v1
kind: Secret
metadata:
    name: docsrv-token
    namespace: default
type: Opaque
stringData:
    token: ENC[AES256_GCM,data:i7Ci+nSQpGrAf+O4asEAxQUaOZM=,iv:obWvVPGnLkWvPSSlJkqQZAQXpGTSISXAXof5OyxD7NE=,tag:hSP/dfJOWT6Pn8slIcg9Sw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-10-07T14:34:31Z"
    mac: ENC[AES256_GCM,data:79Z0TgNiV/7f/j6XI3Yl8yH+Wn+2T68I4PRt5rU2rk8sAEE9krQZl78QkaAhFXkDRUFD3XT5GmD1tJ6yUOmr5JzwyUam9YOmQYdXWBqYtoVuGGto8feoUJhpk6hKcBZWYseBRrT9KiBFUtdVgjdVdrjILbP5rKE3qQgxycb/WW4=,iv:ZIrXBUfvWwY6oPgyZuCOWhHe5yIMgw1oKwALgGrfS0Y=,tag:GOPw5SXwHxi5yR9w14VWWQ==,type:str]
    pgp:
        - created_at: "2022-10-07T14:34:31Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA70fE7dz6LU0AQ//fewjucMctkqB98DlRPeqKYNuNmPenIwgMdSIrcaPnvZy
            zG1yHuW8H+8F7yNnxEBp2mtHpXDfeSi7/7cdTA+1xXzQFbJi3X6S1I6NFxQHH5cN
            oXSKqloqiJ7OfxxfoyUg79RwD/mFTtWW5b1vqDb2N0ZvEWjEKgIvDqRtN3mt0f0w
            EEA9IiLr8JGyRDOSq9MYtd7WL0+Xxr+dMmVFK2NhntyucpRyU7rY4vZvDOQ4xDza
            Zb3Qqq0snefURGjY5B+d1wv9FJXlpfE6G15b9WTK+QVWdkL9OBVvG6W4nVYYO/fd
            JCDq3gXBBzslYPEPser42oV92U54y+h3RaM3BiCdWqmox5F+WPZTd2ianVaikpaE
            Ec4T9XgkiT9gXG3nrkj5OyKEkkS8KsjUOZ1w+PpOPgKjj3tpWb54FzDKw1Ob8vIX
            fRkjjuSSVRo/cUqsVMz/WAJnSzXF4NFq5mPO20sjLYPxC/lU/lEDh1FzV9n/RzHN
            M98N31TDyGLXRFMY8D9o1atOPdtPONqlzynbUxK8Dx4KqgGZgzdCqO0pU8aSaJvs
            z1giSw7L8WET4xaezAFN8UqqstBrZ4TpbAZAl9h/GJSi8c6BhD0v4PeVDpZHmubB
            V27gY+zEU3yGjhCn6xHtOD1bIhM64mdaOvqj2wPa0Sg+Ngqxglr1zr/NQKtevvHS
            XgHYzHfRGQFIaAeHxpsVICn8GvI6aeaaM6xWjFtM+t76DjfO8YcCKQLIuERFigeN
            /nYTLDRXeC6KxU/hrhjbDmiBv4cKG76Kip2pbXPeNqia2w+Lus2Wo30mEqdpS2Q=
            =p4TP
            -----END PGP MESSAGE-----
          fp: 1DF23F1E7AFCAB40F26B210123CFBB30193553AA
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
