apiVersion: v1
kind: Secret
metadata:
    name: docsrv-token
    namespace: default
stringData:
    token: ENC[AES256_GCM,data:Ov15e1upplMBskitV9F48q7nvE8=,iv:kkLo4DavYQO17SwXbssKc7xq8HGFavDUlbXJfuKthio=,tag:jFM+vqOVtRXiMLH2uphD7w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-10-07T14:29:04Z"
    mac: ENC[AES256_GCM,data:6MyoEZuq8IJz/Fxcx2MsqdId6dAhX0vUZ1tMa+YNl/QXlH3ecSNwjPA3x43jFnYGaK+S+/T4GK7kJFixNOdVP5glfWWq/l7QsmgttJMdO+L6P/WjQqti2fKt3jY/2/lD8z83x0NM+1hwOwp65P/82+J5LRsgw2VC2nnMu7BXsy8=,iv:RN1RvZMWF2YcoARn/u64yxS+NFq7Ml7vAZ2oteeKEvY=,tag:XU8+5S8PPJEgGi7DCSZpVQ==,type:str]
    pgp:
        - created_at: "2022-10-07T14:29:04Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA70fE7dz6LU0AQ//f4XF0jKAKbiG06wQhJ0Ipo3xSZ0IvlQhQWxh0HbE+tm6
            dipOZhPUBuGzDInLofjYNl5s1REqNFn+riwSsizfB1o7dJP4NipvJ6PWbWGY1wEM
            AOInBGO6nJb9NamozkoGnW1yBCh0vI7eRtbURlE1OJ/aCYFCxXkid3LqVt64DTxt
            Qp6IEqUiiGD2uEOIGD4Ff0ZprVRD7K+/jRvo1Xx3ALdU/NcV9tWXiR1XO7NAzxCQ
            kUS3+txWLn/gk0/7TnFR9AbE+RXJUf0bDZcGK/r1ksUYe849GiQCiuu8E4s+WDMh
            A/PCesqyQFB4gWm5oVlI/p/7dVDu1Hpr8LJqlHnzfPuEIE1UguiDQxWKyFzozAEj
            m+LGI48eBhcIBfrQXB4LB2NW32A9bRNRg+/HuU87drENg6axdzHGTh5MnQ3Q+U3Z
            jYEAaSCiDK2RDcrYNUGBJR4uPrASTwxBi12nZAuPzBzx40yV9hebdn7/oSobM4ge
            oxsS99giGlLU/MbehI2BTx2iR+u4TpYjOSN7CHtnEg4dD4UkGftGymB7nEOOkDnE
            /D05U07qib3G+OueQcbj91ExpBWTsD9azt1F8RuBqc+FHRjq5B9NHlIQdYPnK6Ph
            F+L+NlkkpHZyo9O538gaS7X8DpW4vWz+ZRM8PBELeLyh8tcsJukvknVs3rxLZ6TS
            XgER80AKPOLkQHJ8A67S+mPeikhgBc/hiG8HdV6PF4yBR3Z/wMlSEsKAxeMA7Erq
            /D17Q5CLmWjLbwSiPeDnyzhAiReeTyHfbv44T5vuVy1ZJ5L+8hjdoQw58k2X1NQ=
            =LauX
            -----END PGP MESSAGE-----
          fp: 1DF23F1E7AFCAB40F26B210123CFBB30193553AA
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
