apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: promtail
  namespace: monitoring
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://grafana.github.io/helm-charts
      chart: promtail
      version: 6.16.2
      sourceRef:
        kind: HelmRepository
        name: grafana-charts
        namespace: flux-system
      interval: 5m
  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  values:
    containerSecurityContext:
      readOnlyRootFilesystem: true
      capabilities:
        drop:
          - ALL
      allowPrivilegeEscalation: false
      privileged: false
    podAnnotations:
      container.apparmor.security.beta.kubernetes.io/promtail: runtime/default
      seccomp.security.alpha.kubernetes.io/pod: runtime/default
    resources:
      limits:
        cpu: 200m
        memory: 128Mi
      requests:
        cpu: 100m
        memory: 128Mi
    config:
      clients:
      - url: http://loki-loki-distributed-gateway/loki/api/v1/push
      snippets:
        extraRelabelConfigs:
          - target_label: host
            replacement: k3s.i.${DOMAIN}
