apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - sts.yml
  - service.yaml
configMapGenerator:
  - name: postfix-config
    namespace: default
    files:
      - main.cf
      - master.cf
