apiVersion: v1
kind: Service
metadata:
  name: backup-mx
  namespace: default
spec:
  type: LoadBalancer
  selector:
    app: backup-mx
  ports:
    - protocol: TCP
      port: 25
      targetPort: 25
      name: mail
    - protocol: TCP
      port: 587
      targetPort: 587
      name: mail-secure
