persistence:
  enabled: true
  useExisting: true
  name: influxdb2

ingress:
  enabled: true
  ingressClassName: traefik
  hostname: influxdb2.k3s.i.stabl.one
  tls: true
  secretName: influxdb2-cert
  annotations:
    kubernetes.io/ingress.class: traefik
    cert-manager.io/issuer: freeipa-issuer
    cert-manager.io/issuer-group: certmanager.freeipa.org
    cert-manager.io/issuer-kind: ClusterIssuer
    cert-manager.io/common-name: influxdb2.k3s.i.stabl.one
    traefik.ingress.kubernetes.io/frontend-entry-points: http,https
    traefik.ingress.kubernetes.io/redirect-entry-point: https


resources: 
  limits:
    cpu: 1000m
    memory: 500Mi
  requests:
    cpu: 125m
    memory: 250Mi

# Security
podAnnotations: 
  container.apparmor.security.beta.kubernetes.io/influxdb2: runtime/default
  seccomp.security.alpha.kubernetes.io/pod: runtime/default

securityContext:
  privileged: false
  allowPrivilegeEscalation: false
  runAsNonRoot: true
  runAsUser: 1000
  runAsGroup: 1000
  capabilities:
    drop:
      -  ALL