apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ingress-nginx.yml
  - metallb-system.yml
  - cert-manager.yml
  - websites.yml
  - monitoring.yml
  - ffsync.yml
  - security.yml
  - longhorn.yml
  - media.yml
  - external-ingress.yml
  - nextcloud.yml
  - cloudflare-tunnel.yml
