apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ingress-nginx.yml
  - metallb-system.yml
  - cert-manager.yml
  - websites.yml
  - monitoring.yml
  - ffsync.yml
  - documentserver.yml
