apiVersion: v1
kind: Secret
metadata:
    name: ip-updater-secret
stringData:
    CF_TOKEN: ENC[AES256_GCM,data:VZVf7D/n/8rp1nnPPCLUbO2gZcBOPfL6QtMJX2oYvmbzSKw/qM2e6g==,iv:7sjsEZwgiZgB/U8qMgX1cYWFvV7ADXXVpObW2ubTURQ=,tag:5upHPncxNJKEH4P6oFn3wQ==,type:str]
    dynv6_token: ENC[AES256_GCM,data:AGZdOCOzw1EnQzNy6wEFNckEmMnngaW0AtIZ/kXW,iv:xZirkCN+rRhLbh0PteCN40RTZK1xV/xZfIzBaeUTAuY=,tag:3eAjBRGcHTB5P6oSCIdzPg==,type:str]
#WARNING: You should not place the username and password in the version control repository or anywhere else in plain text.
#Instead, use the Services Tool Window -> Kubernetes -> <Desired Cluster> -> Configuration -> <right-click on Secrets> -> Create New Secret...
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2024-07-25T22:26:30Z"
    mac: ENC[AES256_GCM,data:pjlFL9N6tpJBgAHG3s+7/S89rGGpoS1+My3Vua/OhT12B+WJQJaWdHp2zzMHMMaQpSbDXRAcZ5QoLM38weIHiHCu55gDBa0CQssi8vC9feM2tIJciSAsxO1S4+Q6CiRwo+Td5kxS4BncB/VT0RmAERtjuc0mJAneBOgoOepLF/Q=,iv:KLTtx2O/b7JcyCokDXgGlXdobokaAK9nfJajSuWxsks=,tag:0kEfqhE3x5pZV8ASaGDYZw==,type:str]
    pgp:
        - created_at: "2024-07-25T20:45:38Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA70fE7dz6LU0AQ//V0mRApK3rqvGxcgA8NauS+ZG4Pcu4t++dK5/NXtKEBqf
            6c7NcXMRSVboa7xhkd8U0LZ/IFfaYl/8TDAfwQDqrP6BmpaEYqApl6jaUdz4tQVS
            D80urItuPS4IttHL/ew3GyC7slMZyKpMD81MkNiFa8aUueS0ouG2egTwt9SBK1B3
            PuZBdc21MdH8sVJ9VrLknRuyuFHkjZTlWNCzP1g7AF+hKovnA6bPT6CSPfZEVkT0
            sA2iVc/JrzV6GOqdFpkVRuhsJtFB/3v318kUCxAYReeLISzX9IbiiD3Mgd9sQnxG
            yOWfC66NTYkhEJF/s+3y4eVGlZAPDg3H/4WEK7N1XjBwe5GpDLbipOwcro487izq
            VmDTtcJ+KKRcBtmyU9rzNE3FWZw+CH04iHxnr4hgW1Ou4Fuv8n4kvqMJOa19IqNV
            rNWXkmzUruX5DbBLkZtrBRHkfb0M1ibcs93HFJ2ZjyguTUp8Flo8orwic4gpD1eq
            4ijz+yW/Or5fmJCvd4z2CGA1rq9eHW1lS2xCt0Ki3nA+1OwevLxlQovhXA4PIoo/
            a06tukdQ9E1TwzMfujpTOEFhGO3ohmXi1QuWUfIOj+LbqCkh1Onjl3zUv8APMOPG
            jEnLvTrNcH3NHE6Bx740eO5IWN2VtXw35S3CTzfyRydusvRKoU+RFJOh27YtT3PS
            XgHozLQDlV8hUmNkOyaT6Cg9NtpIkBpxCvON14TsSaB/i4XGmR7RlSOKnD5Hl1d4
            B7WGurztlxoW7iZd/MZ8Xl4Q8pTuN3RM573e/r9t5ZPyJlUyKOEDbQujTGJ7oBM=
            =8t/H
            -----END PGP MESSAGE-----
          fp: 1DF23F1E7AFCAB40F26B210123CFBB30193553AA
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
