# yaml-language-server: $schema=https://json.schemastore.org/ansible-playbook
---
- hosts: k3s-0.i.stabl.one
  become: yes
  become_method: sudo
  tasks:

  - name: get pod 
    community.kubernetes.k8s_info:
      kubeconfig: /etc/rancher/k3s/k3s.yaml
      kind: pod
      label_selectors:
        - app = grafana
    register: pod

  - name: print name
    debug: 
      msg: "Name: {{pod.resources[0].metadata.name}}"
