apiVersion: v1
kind: Secret
metadata:
    name: authelia-db-secret
    namespace: security
type: Opaque
stringData:
    rootPassword: ENC[AES256_GCM,data:kvN0kl7OjkRNkGbw1xkOrg4EwVQBLCvmZoKDiy9KHghAPVIt6WzQPw==,iv:HzfsCVvyw3J8AXqDj1X34bfRPsxNx5GXyrfV1DeQhr8=,tag:Kask3oYV5ZEjb07FFjJDtA==,type:str]
    userPassword: ENC[AES256_GCM,data:k9Gy6WFmvCrQt3RBiXKCmx0erwfBRN5NFIE361qx/RUHwZdomhEfOg==,iv:olI0SXRJHFBpoGqMFhVsIeF43vMNSfDNbtbzOosVVZA=,tag:VPbQ8jqLpM55zvaeCPYtQQ==,type:str]
    replicationPassword: ENC[AES256_GCM,data:2AS5PLUG5HwaGnwFH+3Z7jm6y4vECMYiAlOoxuR5f6ZI9XpYSjilbA==,iv:almz0pCsBMiS9zZG35SvrUoYIXkHyRSgMvOCbQHipRk=,tag:bg4mdeM2o995kQc28izdVQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2023-08-29T12:09:47Z"
    mac: ENC[AES256_GCM,data:HEUvFLbrhh1ODCk20GHelxXvcc1oH/OKp1kt0FDAVQdslJCESCdYLKLqIwsLj/U/Fo3hLFN6pBsPUBtvPmn6H4+xzwuY18e0BNXSkex9LnLklYJ/WMu8mjEmwnbjHsiLeCcQSDyvwcUPyMKPqzsLyNr5Uqq1QCwW3A4a26fgcY4=,iv:a0kRUUUfmE029APrlMewKijgxsDfSKKXeoSau3kVmWc=,tag:SaRzOaKGTXdD12bfFi2hDA==,type:str]
    pgp:
        - created_at: "2023-08-29T12:09:42Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA70fE7dz6LU0ARAAry6oK2zYVR4vuWPs6ZI5KZsqxqiOIRvYWlqlZRpnTgT9
            2Tt50q4XcObQghrxaVgSFQg6gX8XbCQm3d/MBsKfekMCVHF6DvXyk3zngxyety56
            +KBtTLJ2pZYnZQTkGZP2RwPcQlLviZBhwOxLf7Uv4dWajZMayNOu4e+YwmV9dPOU
            B65T+2lvEfNcNkoSRJ6khonXTblEAQqkuPlkspwgArmry4e98Ro/g8dvjwHxAIha
            ckMNdtxfppbzrH+z+HVWlMhfa84bX5A0CREWQNkvb8MZefk1O0WK9crujFwXBPO3
            z+EGSqgVkukgCL2FO0fJU8jc0/6a/rMsuGRJjz3jyNTNhpD+hWjWxIte5OqQepLh
            0IJWFZEJ5JVFGIv7mLJaX1s9aYJ0ahx/33yW5oWH68h6fc9UdFKRct61MQTzNy9M
            mvJ/Tn/4JgKICwV9HJiY029G9P1pjYL1Zo0D2Nzg106k8Pr9lXIUvH6Y0ZJtq8ay
            M6dQdveSDfvkKW0S3bJUsMB2bSosS62PS718HA0Xi5NEAhp1wSeXaf6ExIaeGEjY
            weOQuRIPJE8W/4T4+orr+JumXEK0+/jNsYSQzM8F4u74Tdyua0pIRTRG9AaW1OKt
            a+jpKiNM+fqISbdQoCOwtnq7jq9R9jxmkTGDgGvKnjIziaF55qqftTrKSLfIcTLS
            XgE+dTxu0y0roMvuztidB5LMbXL5kzx0QwLp5QdHIi+sp+6odKCNgRiARfqyL5Od
            Nfh9IMs7ywro+cwKF7m4oWbzCk0WEOyQnQl2WCokMMzAHRtGkvef/yYoIq7LdJo=
            =atPb
            -----END PGP MESSAGE-----
          fp: 1DF23F1E7AFCAB40F26B210123CFBB30193553AA
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
