---
# yaml-language-server: $schema=https://kubernetes-schemas.devbu.io/helmrelease_v2beta1.json
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: postgresql
  namespace: security
spec:
  interval: 15m
  chart:
    spec:
      # renovate: registryUrl=https://charts.bitnami.com/bitnami
      chart: postgresql
      version: 12.12.4
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
  values:
    global:
      storageClass: longhorn
    auth:
      username: authelia
      database: authelia
      existingSecret: authelia-db-secret
      secretKeys:
        adminPasswordKey: rootPassword
        userPasswordKey: userPassword
        replicationPasswordKey: replicationPassword
    architecture: standalone
