- hosts: all
  tasks:
  - name: upgrade all packages
    dnf:
      name: "*"
      state: latest
  - name: install Centos packages
    dnf:
      name:
        - python3
        - ipa-client
        - sudo
        - net-tools
        - nano
