# yaml-language-server: $schema=https://raw.githubusercontent.com/ansible-community/schemas/main/f/ansible.json
---
- hosts: proxy.i.stabl.one
  become: yes
  become_method: sudo
  collections:
    - nginxinc.nginx_core
  vars_files:
  - secrets.yml
  roles:
    - promtail
    - nginx
    - ip_update
    - external_proxy
