# yaml-language-server: $schema=https://json.schemastore.org/ansible-playbook
---
- hosts: proxy.i.stabl.one
  become: yes
  become_method: sudo
  collections:
    - nginxinc.nginx_core
  vars_files:
  - secrets.yml
  roles:
    - nginx
    - ip_update
    - external_proxy
    - promtail