authelia_config_dir: "{{ docker_config_dir}}authelia/"
db_storage: "{{docker_config_dir}}authelia_db"
svc_user: svc_authelia
db_port: 3306
db_name: authelia
db_user: authelia
authelia_bind_user: "uid={{svc_user}},cn=users,cn=accounts,{{base_dn}}"
authelia_network: authelia_net
redis_name: authelia_redis
db_container: authelia_db
