---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jellyfin-config-v1
  namespace: media
  labels:
    app.kubernetes.io/name: &name jellyfin
    app.kubernetes.io/instance: *name
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  storageClassName: longhorn
  volumeName: pvc-d20b43a9-8ad5-4f5d-a9d7-0806fcbc4196
