---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: jellyfin
  namespace: media
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 2.0.3
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  dependsOn:
    - name: intel-gpu-plugin
      namespace: kube-system
    - name: node-feature-discovery
      namespace: kube-system
  values:
    global:
      nameOverride: jellyfin
    defaultPodOptions:
      securityContext:
        runAsUser: 568
        runAsGroup: 568
        fsGroup: 568
        fsGroupChangePolicy: "OnRootMismatch"
        supplementalGroups:
          - 44
          - 5600
          - 226
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: feature.node.kubernetes.io/custom-intel-gpu
                    operator: In
                    values:
                      - "true"
    persistence:
      config:
        enabled: true
        existingClaim: jellyfin-config-v1
        globalMounts:
        - path: /config
          readOnly: false
      media:
        enabled: true
        type: nfs-client
        server: "proxmox0.i.${DOMAIN}"
        path: /Media
        globalMounts:
        - readOnly: true
          path: /media
      transcode:
        enabled: true
        type: emptyDir
        globalMounts:
        - path: /cache
          readOnly: false

    controllers:
      main:
        type: deployment
        containers:
          main:
            image:
              repository: jellyfin/jellyfin
              tag: 10.18.11
              pullPolicy: IfNotPresent
            env:
              TZ: "Europe/Berlin"
            resources:
              requests:
                gpu.intel.com/i915: 1
                cpu: 100m
                memory: 1Gi
              limits:
                gpu.intel.com/i915: 1
                memory: 4Gi
            probes:
              liveness:
                enabled: false
              readiness:
                enabled: false
              startup:
                enabled: false
    service:
      main:
        ports:
          http:
            port: 8096

    ingress:
      main:
        enabled: true
        className: "nginx"
        annotations:
          cert-manager.io/issuer: freeipa-issuer
          cert-manager.io/issuer-group: certmanager.freeipa.org
          cert-manager.io/issuer-kind: ClusterIssuer
          cert-manager.io/common-name: jellyfin.k3s.i.${DOMAIN}
          nignx.ingress.kubernetes.io/force-ssl-redirect: "true"
        hosts:
          - host: jellyfin.k3s.i.${DOMAIN}
            paths:
              - path: /
                service:
                  name: main
                  port: http
        tls:
          - secretName: jellyfin-tls
            hosts:
            - "jellyfin.k3s.i.${DOMAIN}"
