apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: media
resources:
  - config-pvc.yml
  - deploy.yml
  - service.yml
  - ingress.yml
configMapGenerator:
  - name: jellyfin-web-config
    namespace: media
    files:
      - "web-config.json"
