- name: reset iptables
  iptables:
      chain: "{{ item }}"
      policy: ACCEPT
  with_items: [ 'INPUT', 'OUTPUT', 'FORWARD']

- name: flush iptables
  iptables:
    flush: yes

- name: Allow new incoming SYN packets on TCP port 22 (SSH).
  iptables:
    chain: INPUT
    protocol: tcp
    destination_port: 22
    jump: ACCEPT
    in_interface: "{{ local_interface }}"
    comment: Accept new SSH connections.

- iptables:
    action: append
    chain: OUTPUT
    out_interface: tun+
    jump: ACCEPT

- iptables:
    action: append
    chain: INPUT
    in_interface: lo
    jump: ACCEPT
- iptables:
    action: append
    chain: OUTPUT
    out_interface: lo
    jump: ACCEPT
- iptables:
    action: append
    chain: OUTPUT
    destination: 255.255.255.255
    jump: ACCEPT
- iptables:
    action: append
    chain: INPUT
    source: 255.255.255.255
    jump: ACCEPT
- iptables:
    action: append
    chain: OUTPUT
    out_interface: "{{ local_interface }}"
    protocol: udp
    match: multiport
    destination_port: "{{ item.port }}"
    destination: "{{ item.ip }}"
    jump: ACCEPT
  with_items:
    - "{{ vpn_servers }}"
- name: iptables allow to local network
  iptables:
    action: insert
    chain: OUTPUT
    out_interface: "{{ local_interface }}"
    destination: "{{ item }}"
    jump: ACCEPT
  with_items: "{{local_networks}}"

- name: Allow related and established connections
  iptables:
    chain: INPUT
    ctstate: ESTABLISHED,RELATED
    jump: ACCEPT
  become: yes

- name: Allow related and established connections
  iptables:
    chain: OUTPUT
    ctstate: ESTABLISHED,RELATED
    jump: ACCEPT
  become: yes

- name: default to drop output
  iptables:
    chain: OUTPUT
    policy: DROP
- name: default drop INPUT
  iptables:
    chain: INPUT
    policy: DROP
- name: no local dns
  iptables:
    action: insert
    chain: OUTPUT
    out_interface: "{{ local_interface }}"
    destination: "{{ item }}"
    destination_port: 53
    protocol: udp
    jump: DROP
  with_items: "{{ local_networks }}"