nfs_mount:
  - src: 10.13.2.10:/Media
    dest: /mnt/medien
jellyfin:
  extra_transcode_disk: /dev/vdb
  user: svc_jellyfin
  s3:
    user: "{{ vault_jellyfin.s3.user }}"
    password: "{{ vault_jellyfin.s3.password }}"
promtail:
  user: jellyfin #Name of the user from above
  run_as_user: svc_jellyfin
  scrape_configs: # scrape configs for loki
  - job_name: system
    static_configs:
    - targets:
      - localhost
      labels:
        host: "{{ansible_facts['fqdn']}}"
        app: promtail
        agent: promtail
        __path__: /var/log/jellyfin/log*.log
