apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: mariadb-operator
  namespace: db
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://helm.mariadb.com/mariadb-operator
      chart: mariadb-operator
      version: 0.38.0
      sourceRef:
        kind: HelmRepository
        name: mariadb-operator
        namespace: flux-system
      interval: 5m
  values:
    metrics:
      enabled: true
    cert:
      certManager:
        # -- Whether to use cert-manager to issue and rotate the certificate. If set to false, mariadb-operator's cert-controller will be used instead.
        enabled: true
