apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deploy.yml
  - secret.yml
  - svc.yml
configMapGenerator:
  - name: unifi-poller
    namespace: monitoring
    files:
    - poller.conf
