apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: docserver
  namespace: documentserver
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://download.onlyoffice.com/charts/stable
      chart: docs
      version: 1.1.3
      sourceRef:
        kind: HelmRepository
        name: onlyoffice
        namespace: flux-system
      interval: 5m
  values:
    securityContext:
      enabled: true
    docservice:
      replicas: 1
      containerImage: onlyoffice/docs-docservice-de:7.1.1-4
      resources:
        limits:
          cpu: 200m
          memory: 128Mi
        requests:
          cpu: 100m
          memory: 128Mi
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: nginx
        nginx.ingress.kubernetes.io/proxy-body-size: 100m
        cert-manager.io/issuer: freeipa-issuer
        cert-manager.io/issuer-group: certmanager.freeipa.org
        cert-manager.io/issuer-kind: ClusterIssuer
        cert-manager.io/common-name: document-server.k3s.i.${DOMAIN}
      host: document-server.k3s.i.${DOMAIN}
      ssl:
        enabled: true
        secret: onlyoffice-tls
