apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - service.yml
  - route.yml
  - endpoint.yml
configMapGenerator:
  - name: nextcloud-backend-ca
    namespace: nextcloud
    files:
      - ca.crt=nextcloud-backend-ca.pem
    options:
      disableNameSuffixHash: true
      annotations:
        kustomize.toolkit.fluxcd.io/substitute: disabled
