apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - prom-pv.yml
  - prom-pvc.yml
  - prom-sts.yml
  - prom-svc.yml
  - prom-rbac.yml
configMapGenerator:
  - name: prometheus-external-config
    namespace: monitoring
    files:
      - "prometheus.yml"
