global:
scrape_configs:
  - job_name: unifi-poller
    scrape_interval: 60s
    static_configs:
    - targets: ['unifi-poller:9130']
  - job_name: 'prometheus'
    scrape_interval: 60s
    metric_relabel_configs:
    - source_labels: [ __name__ ]
      regex: 'prometheus_http_request_duration_seconds_bucket|prometheus_http_response_size_bytes_bucket'
      action: drop
    static_configs:
      - targets: ['localhost:9090']
  # - job_name: jellyfin
  #   static_configs:
  #     - targets:
  #       - "jellyfin.i.${DOMAIN}:8920"
  #   scheme: https
  #   tls_config:
  #     insecure_skip_verify: true
  - job_name: minio-job
    scrape_interval: 60s
    bearer_token: ${MINIO_PROM_TOKEN}
    metrics_path: /minio/v2/metrics/cluster
    scheme: https
    static_configs:
    - targets: ['s3.i.${DOMAIN}:9000']
  - job_name: nextcloud-exporter
    scrape_interval: 30s
    static_configs:
    - targets: ['nc-exporter:9205']
  - job_name: jellyfin-exporter
    scrape_interval: 30s
    static_configs:
    - targets: ['jellyfin-exporter:8080']
  - job_name: solar-exporter
    scrape_interval: 60s
    static_configs:
    - targets: ['solar-exporter:9090']
  - job_name: 'netdata-scrape'
    metrics_path: '/api/v1/allmetrics'
    metric_relabel_configs:
    - source_labels: [ __name__ ]
      regex: 'prometheus_http_request_duration_seconds_bucket'
      action: drop
    params:
      # format: prometheus | prometheus_all_hosts
      # You can use `prometheus_all_hosts` if you want Prometheus to set the `instance` to your hostname instead of IP
      format: [prometheus]
      #
      # sources: as-collected | raw | average | sum | volume
      # default is: average
      source: [as-collected, average]
      #
      # server name for this prometheus - the default is the client IP
      # for Netdata to uniquely identify it
      #server: ['prometheus1']
    honor_labels: true
    scrape_interval: 60s
    static_configs:
      - targets: ['proxmox0.i.${DOMAIN}:19999']
  - job_name: speedtest-exporter
    scrape_interval: 1h
    scrape_timeout: 5m
    static_configs:
      - targets:
          - "speedtest-exporter:9798"
  # - job_name: keel-exporter
  #   scrape_interval: 30s
  #   static_configs:
  #   - targets: ['keel-exporter.default.svc.cluster.local:8080']
  - job_name: Longhorn
    scrape_interval: 60s
    metric_relabel_configs:
    - source_labels: [ __name__ ]
      regex: 'longhorn_rest_client_.*'
      action: drop
    kubernetes_sd_configs:
    - role: pod
      # api_server: 'https://kubernetes'
      # tls_config:
      #   ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
      # bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
      namespaces:
        names:
        - longhorn
      selectors:
      - role: "pod"
        label: "app=longhorn-manager"
    metrics_path: /metrics
  - job_name: 'blackbox'
    metrics_path: /probe
    params:
      module: [http_2xx]  # Look for a HTTP 200 response.
    static_configs:
      - targets:
        - https://ffsync.${OLD_DOMAIN}
        - https://s3.i.${DOMAIN}:9091
        - https://ipa.i.${DOMAIN}
        - https://ipa0.i.${DOMAIN}
        - https://ipa1.i.${DOMAIN}
        - https://influxdb2.k3s.i.${DOMAIN}
        - http://loki-loki-distributed-gateway/
        - https://unifi.${DOMAIN}
        - https://docsrv.${DOMAIN}
        - https://auth.${DOMAIN}
        - https://cloud.${DOMAIN}
        - https://stream.${DOMAIN}
        - https://proxmox0.i.${DOMAIN}:8006
        - https://syncserver.k3s.i.${DOMAIN}
        - http://syncserver.ffsync.svc.cluster.local:5001
        - http://kube-prometheus-stack-prometheus:9090

    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: prometheus-blackbox-exporter:9115  # The blackbox exporter's real hostname:port.
  - job_name: 'blackbox_exporter'  # collect blackbox exporter's operational metrics.
    static_configs:
      - targets: ['prometheus-blackbox-exporter:9115']
