apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prometheus-external
  namespace: monitoring
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: nfs-client
  volumeName: prometheus-external-vol-0
