apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prometheus-external-longhorn
  namespace: monitoring
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 35Gi
  storageClassName: longhorn
