apiVersion: v1
kind: PersistentVolume
metadata:
  name: prometheus-external-vol-0
spec:
  capacity:
    storage: 10Gi # must match size of Longhorn volume
  volumeMode: Filesystem
  nfs:
    path: /NVMe/k3s/monitoring-prometheus-external-vol-0
    server: 10.13.2.10
  accessModes:
    - ReadWriteMany
  # persistentVolumeReclaimPolicy: Delete
  storageClassName: nfs-client # must be same name that we will use later
