apiVersion: apps/v1
kind: Deployment
metadata:
  name: speedtest-exporter
  namespace: monitoring
  labels:
    app.kubernetes.io/name: speedtest-exporter
    app.kubernetes.io/instance: speedtest-exporter
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: speedtest-exporter
  template:
    metadata:
      labels:
        app.kubernetes.io/name: speedtest-exporter
        app.kubernetes.io/instance: speedtest-exporter
    spec:
      enableServiceLinks: false
      securityContext:
        runAsNonRoot: true
        runAsUser: 568
        runAsGroup: 568
        fsGroup: 568
        fsGroupChangePolicy: OnRootMismatch
        seccompProfile:
          type: RuntimeDefault
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: kubernetes.io/hostname
          whenUnsatisfiable: DoNotSchedule
          labelSelector:
            matchLabels:
              app.kubernetes.io/name: speedtest-exporter
      automountServiceAccountToken: false
      containers:
        - name: speedtest-exporter
          image: ghcr.io/miguelndecarvalho/speedtest-exporter:v3.5.4
          ports:
            - name: http
              containerPort: 9798
              protocol: TCP
          resources:
            requests:
              cpu: 250m
              memory: 10Mi
            limits:
              memory: 200Mi
          securityContext:
            readOnlyRootFilesystem: true
            allowPrivilegeEscalation: false
            capabilities:
              drop: [ "ALL" ]
          livenessProbe:
            httpGet:
              path: /
              port: 9798
            initialDelaySeconds: 0
            periodSeconds: 10
            timeoutSeconds: 1
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /
              port: 9798
            initialDelaySeconds: 0
            periodSeconds: 10
            timeoutSeconds: 1
            failureThreshold: 3
