apiVersion: v1
kind: Service
metadata:
  name: speedtest-exporter
  namespace: monitoring
  labels:
    app.kubernetes.io/name: speedtest-exporter
    app.kubernetes.io/instance: speedtest-exporter
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 9798
      targetPort: 9798
      protocol: TCP
  selector:
    app.kubernetes.io/name: speedtest-exporter
