apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: postgresql
  namespace: documentserver
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://charts.bitnami.com/bitnami
      chart: postgresql
      version: 11.9.6
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
      interval: 5m
  values:
    primary:
      podAnnotations:
        container.apparmor.security.beta.kubernetes.io/postgresql: runtime/default
        seccomp.security.alpha.kubernetes.io/pod: runtime/default
      containerSecurityContext:
        capabilities:
          drop: ["ALL"]
        readOnlyRootFilesystem: false
        enabled: true
        runAsUser: 1001
        runAsNonRoot: true

      persistence:
        storageClass: nfs-client
        size: 1Gi
    resources:
      limits:
        cpu: 200m
        memory: 128Mi
      requests:
        cpu: 100m
        memory: 128Mi
    #
    auth:
      database: postgres
