apiVersion: v1
kind: Secret
metadata:
    name: unifi-mongodb-secret
    namespace: default
    labels:
        app: unifi
type: Opaque
stringData:
    #ENC[AES256_GCM,data:LB7O2On/9kxjNPjf6UopG6Qo0dcH+1Qo61JTXiUILwuTgQKi2eBzFNQNkftt3cFh3Gut8iRiM9aFvcfYLIcZTWAHjkhY2A==,iv:Yhi2ZcKE+c9A+PboSys4niNZBLGDjFcCc+KWXogQ85g=,tag:80Kic2ghYiEgrZScyh12JA==,type:comment]
    MONGO_ROOT_PASSWORD: ENC[AES256_GCM,data:31x86QK+wNNwuhiIGyrn3Rh7AILqG5wILV9dz+6iF+ArgU0KRBnrUAanTWzmiYqa/A==,iv:woA8wYF3n1AD96t3SAl6EFSGX6yldKIpFFa7N97s0wE=,tag:tGUB6GGRXuqDII8OAuj56g==,type:str]
    #ENC[AES256_GCM,data:PlJ+XLw3cb2eKeKxJlUEg7fvCFIxEyDjR4pKobCmI33ZgsPAG+Mn56gGIE9hXACbFhaMvyUDXpxnqg8e6MTsM3BrRASoINgDOWg9puGBkcX9e9Ys,iv:kRPzLcsqMtUiRSCxB49G+7Wq/e+qX+hMeEU2L7X+6k0=,tag:lQ33vs2GN1Wybs06VmTzsw==,type:comment]
    MONGO_PASS: ENC[AES256_GCM,data:+xyxhOidLTUzY3mbJ5kCSY4vpDJOtKfHNZnKIcbFvJGDfvqPXfzygPDKTcaOtgfB0Q==,iv:acpFA0DLgdCiqLEiMI9g8539Ij6LzKcZX8+sqAmy9WQ=,tag:LRJK+sK/hQECmlixfjky+Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2026-05-26T18:44:55Z"
    mac: ENC[AES256_GCM,data:XhQupLVnnnSPD0xWeUDARYsDfFrB+UiGOy6xxatMYjU3HZZAgZ++oUau3g1CGa1/Wt/WFJIz9h1xOMDpmLpypUzc13AedrrB99USPEZaC17lvkgGB2dsAZ6tnhd4yT+jM7VQoccQQWLttInpNkxja9cTqs6sq2y02zidHpUoueo=,iv:yCxcrD94tMPq50vs2nuIR7zDScrXym9Uyy7siP9R8K4=,tag:9c01pH56m6qSmStBjulVqg==,type:str]
    pgp:
        - created_at: "2026-05-26T15:47:01Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA70fE7dz6LU0ARAAi0oB4X+RlkEfQDEhs3MISnlk8vEQzOugLITx10OSOnWm
            Cbli/VO7m6UtamJUqCRgYAG+1J6AETmfkrGwAATnmZTpAzu3cH+37z0mOa2WKeyD
            AAWlcM1fA7zLlKdrx9yrEpcC/d3XXVA1qFsVN5EzuPFavjtbPCgtVRhaHP02+SEG
            ux4gf5P/XyhTkl9CWe+1/rK1M3gYQzylgthAr3dFFqMEjS5VnjyphRMuhqNQ26Kj
            CvRwcOB3qFXmNBXx8/Rdl88XUK3aerLbrtLeCbKJVxq0d/tVY2oBjNgbXiv6f3rv
            hvrQMGAHdR6NOlOMUyiD4bmMUNj5xQkC+TnbwaV2SRbkKh90dtilqqNq27emo7eT
            jGRFspE2TcMR+VDE/0g14clqKotejvZnpPNEjbiLCBjpuyDIUdcb4WwM8l8zJ/1i
            jPs/Wt/3NtMG+CL/tKVBfblkWFtE3LpAuSTtCAiziuezA6TFj3ZDXYkoq07ILJTs
            Xzu8dvWdj6SytwEXwAT4r+rLhA+cnnm/fvpDTFnXCGezhHpbsFGHoSSX+1RKQgn+
            JQL2uA7V5TOkGKMCOWMY7zCaa5PNtA3pL0BtGFMOY15G1SmYEjNAtaLTA/Mdq2Tg
            srd2oOXv2I6pjDVs/WbKABQDXND5Ro+6lZ8WWq7GToV2yBpF8GtaC7Gg57pz09/S
            XgEHo4/zmm1QPlbJa53mitmDYwEuypD+klDxd2Vn0pgNziS8gywq/OX10o0J9TXW
            cO3FSVm1K5SENsgjcWYrlAdS5vhxngqm26vEqtyXDxSIVF5k9MhUNgrE9jF2kh4=
            =hoOa
            -----END PGP MESSAGE-----
          fp: 1DF23F1E7AFCAB40F26B210123CFBB30193553AA
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
