apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: unifi
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 12Gi
  storageClassName: longhorn
  volumeName: pvc-cca0ba5c-107c-430b-831f-ab5c2f4896c1
