apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: unifi
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: longhorn
