apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: unifi
  namespace: default
spec:
  selector:
    matchLabels:
      app: unifi
  serviceName: unifi
  replicas: 1
  template:
    metadata:
      labels:
        app: unifi
      annotations:
        container.apparmor.security.beta.kubernetes.io/unifi: runtime/default
        seccomp.security.alpha.kubernetes.io/pod: runtime/default
    spec:
      securityContext:
        runAsUser: 999
        runAsGroup: 999
      initContainers:
      - name: fix-permissions
        image: busybox
        command: ["sh", "-c", "chown -R 999:999 /unifi"]
        securityContext:
          runAsUser: 0
          runAsNonRoot: false
        volumeMounts:
          - name: unifi
            mountPath: /unifi
      containers:
        - name: unifi
          image: jacobalberty/unifi:v8.0.24
          env:
            - name: TZ
              value: EUROPE/BERLIN
            - name: UNIFI_STDOUT
              value: "true"
          ports:
            - containerPort: 8080
              name: inform
            - containerPort: 8443
              name: ui
            - containerPort: 3478
              name: stun
              protocol: UDP
          volumeMounts:
            - name: unifi
              mountPath: /unifi
            - name: tmp
              mountPath: /tmp
          resources:
            requests:
              memory: 1Gi
              cpu: 250m
            limits:
              memory: 2Gi
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            privileged: false
            readOnlyRootFilesystem: true
            runAsNonRoot: true
      volumes:
        - name: tmp
          emptyDir: {}
        - name: unifi
          persistentVolumeClaim:
            claimName: unifi
      automountServiceAccountToken: false
  updateStrategy: {}
