apiVersion: v1
kind: PersistentVolume
metadata:
  name: influxdb2-vol-0
spec:
  capacity:
    storage: 10Gi # must match size of Longhorn volume
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  # persistentVolumeReclaimPolicy: Delete
  csi:
    driver: driver.longhorn.io # driver must match this
    fsType: ext4
    volumeAttributes:
      numberOfReplicas: "2" # must match Longhorn volume value
      staleReplicaTimeout: '30' # in minutes
    volumeHandle: pvc-54635041-d51e-4e7e-820f-8f5a3ae0e6e7 # must match volume name from Longhorn
  storageClassName: longhorn # must be same name that we will use later
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: influxdb2
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: longhorn
  volumeName: influxdb2-vol-0