persistence:
  enabled: true
  useExisting: true
  name: influxdb2

ingress:
  enabled: true
  ingressClassName: traefik
  hostname: influxdb2.k3s.i.stabl.one
  tls: true
  secretName: influxdb2-cert
  annotations:
    kubernetes.io/ingress.class: traefik
    cert-manager.io/issuer: freeipa-issuer
    cert-manager.io/issuer-group: certmanager.freeipa.org
    cert-manager.io/issuer-kind: ClusterIssuer
    cert-manager.io/common-name: influxdb2.k3s.i.stabl.one
