apiVersion: v1
kind: PersistentVolume
metadata:
  name: prometheus-stack
  namespace: monitoring
spec:
  storageClassName: longhorn
  capacity:
    storage: 10Gi
  accessModes:
  - ReadWriteOnce # required
