apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prometheus-stack
  namespace: monitoring
  labels:
    app-name: prometheus-stack
spec:
  resources:
    requests:
      storage: 15Gi
  storageClassName: longhorn
  accessModes:
    - ReadWriteOnce
