apiVersion: v1
kind: PersistentVolume
metadata:
  name: prometheus-external-vol-0
spec:
  capacity:
    storage: 10Gi # must match size of Longhorn volume
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  # persistentVolumeReclaimPolicy: Delete
  csi:
    driver: driver.longhorn.io # driver must match this
    fsType: ext4
    volumeAttributes:
      numberOfReplicas: "2" # must match Longhorn volume value
      staleReplicaTimeout: '30' # in minutes
    volumeHandle: pvc-31d0e766-ad38-474c-b511-1ad4404a19cb # must match volume name from Longhorn
  storageClassName: longhorn # must be same name that we will use later
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prometheus-external
  namespace: default
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: longhorn
  volumeName: prometheus-external-vol-0