- name: Create a ext4 filesystem on /dev/vdb
  community.general.filesystem:
    fstype: ext4
    dev: "{{ jellyfin.extra_transcode_disk }}"
- name: Configure virtual disk for transcode directory
  ansible.posix.mount:
    src: "{{ jellyfin.extra_transcode_disk }}"
    path: /transcode
    opts: defaults
    state: mounted
    fstype: ext4
- name: Allow Jellyfin user access to transcode directory
  file:
    path: /transcode
    state: directory
    owner: "{{ jellyfin.user | default('jellyfin', true) }}"
    group: "{{ jellyfin.user | default('jellyfin', true) }}"
    recurse: yes
