- name: template streams
  ansible.builtin.template:
    src: stream.conf
    dest: /etc/nginx/streams/{{item.name}}
  with_items: "{{streams}}"
- name: Find streams which are no longer specified
  find: 
    paths: 
      - /etc/nginx/streams
    excludes: "{{streams | map(attribute='name') | list }}"
  register: found_streams
  changed_when: False
- name: Remove sites which are no longer specified
  file: 
    path: "{{ item }}"
    state: absent
  with_items: "{{found_streams['files'] | map(attribute='path') | list}}"