apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: minio-loki
  namespace: monitoring
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://charts.min.io/
      chart: minio
      version: 5.1.0
      sourceRef:
        kind: HelmRepository
        name: minio-charts
        namespace: flux-system
      interval: 5m
  values:
    mode: standalone
    replicas: 1
    resources:
      requests:
        memory: 500Mi
        cpu: 200m
      limits:
        memory: 2Gi

    affinity:
      nodeAffinity:
        preferredDuringSchedulingIgnoredDuringExecution:
        - weight: 1
          preference:
            matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
              - worker02.i.${DOMAIN}
              - worker03.i.${DOMAIN}


    persistence:
      enabled: true
      storageClass: longhorn
      size: 40Gi
    users:
    - accessKey: "${LOKI_MINIO_USER}"
      secretKey: "${LOKI_MINIO_PASS}"
      policy: readwrite
    buckets:
     - name: loki
       policy: none
       purge: false
       versioning: false
       objectlocking: false
