---
- name: Compose the Minio server download base url
  set_fact:
    _minio_server_download_base_url: "https://dl.minio.io/server/minio/release/linux-amd64"

- name: Compose the Minio server download url with lastest release
  set_fact:
    _minio_server_download_url: "{{ _minio_server_download_base_url }}/minio"
  when: minio_server_release | length == 0

- name: "Compose the Minio server download url with release {{ minio_server_release }}"
  set_fact:
    _minio_server_download_url: "{{ _minio_server_download_base_url }}/archive/minio.{{ minio_server_release }}"
  when: minio_server_release | length > 0

- name: "Get the Minio server checksum for {{ go_arch }} architecture"
  set_fact:
    _minio_server_checksum: "{{ lookup('url', _minio_server_download_url + '.sha256sum').split(' ')[0] }}"

- name: Download the Minio server
  get_url:
    url: "{{ _minio_server_download_url }}"
    dest: "{{ minio_server_bin }}"
    owner: "root"
    group: "root"
    mode: 0755
    checksum: "sha256:{{ _minio_server_checksum }}"
  register: _download_server
  until: _download_server is succeeded
  retries: 5
  delay: 2
  notify: restart minio

- name: Generate the Minio server envfile
  template:
    src: minio.env
    dest: "{{ minio_server_envfile }}"
    owner: "root"
    group: "{{ minio.service_account.name }}"
    mode: 0640
  notify: restart minio

- name: Create the Minio server systemd config
  template:
    src: minio.service
    dest: "/etc/systemd/system/minio.service"
    owner: "root"
    group: "root"
  when: ansible_service_mgr == "systemd"
  notify:
    - reload minio systemd
    - restart minio
- name: Enable and start the Minio service
  service:
    name: minio
    state: started
    enabled: true