- name: Install Minio Server
  include_tasks: server.yml
  args:
    apply:
      become: yes
- name: Install Minio Client
  include_tasks: client.yml
  args:
    apply:
      become: yes
- name: Flush handlers
  meta: flush_handlers
- name: Wait for port 9000
  wait_for:
    port: 9000
    host: 'localhost'
- name: Add Server to MC command
  become: true
  async: 180
  poll: 5
  shell: timeout 1m bash -c 'until (mc config host add local https://"s3.{{internal_domain}}":9000 "{{minio.root_user.name}}" "{{minio.root_user.pass}}"); do sleep 1; done;'
  #until (mc config host add local http://localhost:9000 "{{minio_root_user}}" "{{minio_root_pass}}") do echo waiting && sleep 1; done;
  #mc config host add local http://localhost:9000 {{minio_root_user}} {{minio_root_pass}}
  #until (/usr/bin/mc config host add myminio http://storage:9000 minioadmin minioadmin) do echo '...waiting...' && sleep 1; done;

- name: Grant access to Minio Console to FreeIPA user {{ ipa_admin_user }}
  become: true
  command:
    argv:
      - mc
      - idp
      - ldap
      - policy
      - attach
      - local
      - consoleAdmin
      - --user
      - 'uid={{ipa_admin_user}},cn=users,cn=accounts,{{base_dn}}'
  register: resp
  failed_when: resp.rc != 0 and "The specified policy change is already in effect." not in resp.stderr

- name: Create Minio buckets
  become: true
  command:
    argv:
     - mc
     - mb
     - "local/{{ item }}"
     - --ignore-existing
  with_items:
    - "{{minio_server_buckets}}"

- name: Create Service accounts
  with_items:
  - "{{minio_server_svcaccts}}"
  include_tasks: create_svcacct.yml
