acme_sh_upgrade: False
acme_sh_account_email: "{{ipa_admin_user}}@{{domain_name}}"
acme_sh_default_staging: False
acme_sh_default_force_issue: False
acme_sh_default_dns_provider: "dns_cf"
acme_sh_default_dns_provider_api_keys:
  "CF_Token": "{{minio.cf_token}}"
  "CF_Zone_ID": "{{CF_Zone_ID}}"
acme_sh_domains:
  - domains:
    - "s3.{{internal_domain}}"
    staging: False
    force_issue: True
    issue_post_hook: "chown svc_minio /etc/ssl/ansible/s3.{{internal_domain}}/private.key"

s3_data_dir: /Volume2/s3

minio_server_opts: "--certs-dir /etc/ssl/ansible/s3.{{internal_domain}}/"
minio_server_env_extra: |
  MINIO_SERVER_URL=https://s3.i.stabl.one:9000
  _MINIO_DISK_ACTIVE_MONITORING=off
  _MINIO_DRIVE_ACTIVE_MONITORING=off
minio_server_datadirs:
  - /Volume2/minio
minio_server_buckets:
 - longhorn
 - mail-backup
 - db-cluster
minio_server_svcaccts:
  - name: "{{longhorn.s3_user}}"
    pass: "{{longhorn.s3_pass}}"
    bucket: longhorn
  - name: "{{ mailserver_s3_access_key }}"
    pass: "{{ mailserver_s3_secreet_key }}"
    bucket: mail-backup
  - name: "{{ db_backup_user }}"
    pass: "{{ db_backup_secret }}"
    bucket: db-cluster

promtail:
  user: "{{ansible_facts['hostname']}}" #Name of the user from above
  create_user: true
  scrape_configs: # scrape configs for loki
  - job_name: system
    pipeline_stages:
    - json:
        expressions:
          timestamp: timestamp
    - timestamp:
        source: timestamp
        format: unix
    static_configs:
    - targets:
      - localhost
      labels:
        host: "{{ansible_facts['fqdn']}}"
        app: promtail
        agent: promtail
        __path__: /tmp/hdparm_reports.json

hdparm_reports_output_file: /tmp/hdparm_reports.json

swap_size: 4G
