apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monitoring
resources:
  - sts.yml
  - svc.yml
configMapGenerator:
  - name: s3-config
    namespace: monitoring
    files:
      - s3.json
