apiVersion: v1
kind: ConfigMap
metadata:
  name: s3-lifecycle-policy
  namespace: monitoring
data:
  lifecycle-policy.json: |
    {
      "Rules": [
        {
          "ID": "DeleteOldObjects",
          "Status": "Enabled",
          "Filter": {},
          "Expiration": {
            "Days": 60
          }
        }
      ]
    }
