apiVersion: v1
kind: Service
metadata:
  name: seaweed
  namespace: monitoring
spec:
  selector:
    app: seaweed
  ports:
  - port: 8333
    targetPort: s3
    name: s3
  - port: 9091
    targetPort: metrics
    name: metrics
