# yaml-language-server: $schema=https://json.schemastore.org/ansible-playbook
---
- hosts: nextcloud.i.stabl.one
  become: true
  tasks:
  - name: update cronjobs
    include_tasks: ./cronjobs.yml
    vars:
      - disable: false
