# yaml-language-server: $schema=https://json.schemastore.org/ansible-playbook
---
- hosts: nextcloud.i.stabl.one
  vars:
    archive_url: "https://download.nextcloud.com/server/releases/nextcloud-21.0.1.tar.bz2"
    old_version: 20.0.4
  become: yes
  tasks:
    - name: Download new NC version
      get_url:
        url: "{{archive_url}}"
        dest: /tmp/nextcloud.tar.bz2
        checksum: "sha256:{{ archive_url }}.sha256"
    - name: Stop apache
      service:
        name: apache2
        state: stopped
    - name: Disable cronjobs
      include_tasks: ./cronjobs.yml
      vars:
        - disable: true


    - name: backup current installation
      copy: 
        remote_src: yes
        src: /var/www/nextcloud/
        dest: "/var/www/nextcloud-{{old_version}}"

    - name: remove the current installation
      file:
        path: "/var/www/nextcloud/"
        state: absent

    - name: Unpack new NC version
      unarchive: 
        src: /tmp/nextcloud.tar.bz2
        dest: /var/www/
        remote_src: true
        creates: /var/www/nextcloud/occ
    - name: copy config.php
      copy:
        remote_src: true
        src: /var/www/nextcloud-{{old_version}}/config/config.php
        dest: /var/www/nextcloud/config/config.php
    - name: Adjust ownership
      file:
        path: /var/www/nextcloud/
        state: directory
        recurse: yes
        owner: www-data
        group: www-data
    - name: Adjust permissions
      shell: | 
        find /var/www/nextcloud/ -type d -exec chmod 750 {} \;
        find /var/www/nextcloud/ -type f -exec chmod 640 {} \;

    - name: Start apache
      service:
        name: apache2
        state: started

    - name: start updater
      shell: 
        cmd: sudo -u www-data php7.4 occ upgrade --no-interaction
        chdir: /var/www/nextcloud/ 
      register: occ_output
    - name: Print occ output
      debug:
        var: occ_output
    - name: reenable cronjobs
      include_tasks: ./cronjobs.yml
      vars:
        - disable: false
