apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: rabbitmq
  namespace: documentserver
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://charts.bitnami.com/bitnami
      chart: rabbitmq
      version: 10.3.6
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
      interval: 5m
  values:
    extraEnvVars:
      - name: RABBITMQ_COMBINED_CERT_PATH
        value: /tmp/rabbitmq_combined_keys.pem
    extraVolumes:
    - name: certs
      emptyDir: {}
    - name: configfiledir
      emptyDir: {}
    extraVolumeMounts:
    - name: certs
      mountPath: /tmp/
    - name: configfiledir
      mountPath: /opt/bitnami/rabbitmq/etc/rabbitmq/
    podAnnotations:
      container.apparmor.security.beta.kubernetes.io/rabbitmq: runtime/default
      seccomp.security.alpha.kubernetes.io/pod: runtime/default
    containerSecurityContext:
      capabilities:
        drop: ["ALL"]
      readOnlyRootFilesystem: true
      enabled: true
      runAsUser: 1001
      runAsNonRoot: true
    resources:
      limits:
        cpu: 200m
        memory: 128Mi
      requests:
        cpu: 100m
        memory: 128Mi
