
- name: Set variables
  set_fact:
    installFonts: false
    installPackages: true
    extensionsDir: "{{ ansible_env.HOME }}/.zsh/"
    rootExtensionDir: "/root/.zsh/"
- name: install zsh packages
  action: >
    {{ ansible_pkg_mgr }} name={{ item }} state=present update_cache=yes
  with_items:
    - zsh
    - git
    - tar
  become: yes
  when: installPackages

- name: Download p10k
  git:
    repo: https://github.com/romkatv/powerlevel10k.git
    dest: "{{ extensionsDir }}powerlevel10k"
- name: Download zsh-autosuggestions
  git:
    repo: https://github.com/zsh-users/zsh-autosuggestions
    dest: "{{ extensionsDir }}zsh-autosuggestions"

- name: Copy config files
  copy:
    dest: "{{ ansible_env.HOME }}"
    src: "{{ item }}"
  with_items:
  - "{{ lookup('env','HOME') }}/.zshrc"
  - "{{ lookup('env','HOME') }}/.zshrc.zni"
  - "{{ lookup('env','HOME') }}/.p10k.zsh"

- name: make fonts directory
  file:
    path: "{{ lookup('env','HOME') }}/.local/share/fonts"
    state: directory
  when: installFonts
- name: download fonts
  get_url:
    url: "{{ item }}"
    dest: "{{ lookup('env','HOME') }}/.local/share/fonts/"
  when: installFonts
  with_items:
    - "https://github.com/romkatv/powerlevel10k-media/raw/master/MesloLGS%20NF%20Regular.ttf"
    - "https://github.com/romkatv/powerlevel10k-media/raw/master/MesloLGS%20NF%20Bold.ttf"
    - "https://github.com/romkatv/powerlevel10k-media/raw/master/MesloLGS%20NF%20Italic.ttf"
    - "https://github.com/romkatv/powerlevel10k-media/raw/master/MesloLGS%20NF%20Bold%20Italic.ttf"
- name: update fonts
  command: fc-cache -f -v
  when: installFonts


- name: Make sure .bash_profile exists
  file:
    path: "{{ ansible_env.HOME }}/.bash_profile"
    state: touch

- name: update .bash_profile to start zsh on login
  blockinfile:
    dest: "{{ ansible_env.HOME }}/.bash_profile"
    block: |
      if [ "$SHELL" != "/usr/bin/zsh" -a -n "$SSH_TTY" -a -x /usr/bin/zsh ]; then
        export SHELL="/usr/bin/zsh"
        exec $SHELL -l
      fi
      export BASH_ENV=~/.bash_profile

# Repeat as root
- name: Download p10k for root
  git:
    repo: https://github.com/romkatv/powerlevel10k.git
    dest: "{{ rootExtensionDir }}powerlevel10k"
  become: yes
  become_method: sudo
- name: Download zsh-autosuggestions for root
  git:
    repo: https://github.com/zsh-users/zsh-autosuggestions
    dest: "{{ rootExtensionDir }}zsh-autosuggestions"
  become: yes
  become_method: sudo
- name: Copy config files for root
  copy:
    dest: "/root/"
    src: "{{ item }}"
  with_items:
  - "{{ lookup('env','HOME') }}/.zshrc"
  - "{{ lookup('env','HOME') }}/.zshrc.zni"
  - "{{ lookup('env','HOME') }}/.p10k.zsh"
  become: yes
  become_method: sudo
- name: Make sure .bash_profile exists for root
  file:
    path: "/root/.bash_profile"
    state: touch
  become: yes
  become_method: sudo
- name: update .bash_profile to start zsh on login for root
  blockinfile:
    dest: "/root/.bash_profile"
    block: |
      if [ "$SHELL" != "/usr/bin/zsh" -a -n "$SSH_TTY" -a -x /usr/bin/zsh ]; then
        export SHELL="/usr/bin/zsh"
        exec $SHELL -l
      fi
  become: yes
  become_method: sudo
