kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: allow-from-db
spec:
  policyTypes:
  - Ingress
  podSelector: {}
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: db
