apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: mobivey
  labels:
    app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      name: frontend
      labels:
        app: frontend
    spec:
      automountServiceAccountToken: false
      imagePullSecrets:
        - name: image-pull-creds
      containers:
        - name: frontend
          # The comment on the next line is needed for flux image automation
          # https://fluxcd.io/flux/guides/image-update/#configure-image-updates
          image: "ghcr.io/svken/wegetagebuch:20250602154349" # {"$imagepolicy": "mobivey:mobivey-fe"}
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              memory: 300Mi
              ephemeral-storage: 1Gi
            requests:
              cpu: 50m
              memory: 100Mi
          ports:
            - containerPort: 80
              protocol: TCP
      restartPolicy: Always
