version: '2'

services:
  db:
    image: mariadb:10.5
    restart: always
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    volumes:
      - /nextcloud_local/db:/var/lib/mysql
      - /nextcloud_local/secrets/nextcloud_maridb_root_password:/run/secrets/nextcloud_maridb_root_password:ro
      - /nextcloud_local/secrets/nextcloud_db_user_pass:/run/secrets/nextcloud_db_user_pass:ro
      - /nextcloud_local/dbdump/dbBackup.sql:/docker-entrypoint-initdb.d/dbBackup.sql:ro
    environment:
      - MARIADB_ROOT_PASSWORD_FILE=/run/secrets/nextcloud_maridb_root_password
      - MARIADB_PASSWORD_FILE=/run/secrets/nextcloud_db_user_pass
      - MYSQL_DATABASE=owncloud
      - MYSQL_USER=owncloud
  redis:
    image: "redis:alpine"

    command: redis-server

    ports:
     - "6379:6379"

  app:
    image: nextcloud:23.0.0-fpm
    restart: always
    links:
      - db
    volumes:
      - /nextcloud_local/webroot:/var/www/html
      - /data:/data
    # environment:
    #   - MYSQL_PASSWORD=
    #   - MYSQL_DATABASE=nextcloud
    #   - MYSQL_USER=nextcloud
    #   - MYSQL_HOST=db

  web:
    image: nginx
    restart: always
    ports:
      - 8080:80
    links:
      - app
    volumes:
      - /nextcloud_local/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    volumes_from:
      - app
