apiVersion: apps/v1
kind: Deployment
metadata:
  name: solar-exporter
  namespace: monitoring
spec:
  selector:
    matchLabels:
      app: solar-exporter
  template:
    metadata:
      labels:
        app: solar-exporter
    spec:
      containers:
      - name: solar-exporter
        image: ghcr.io/stefanabl/solar-exporter
        tag: 20230702071144
        resources:
          limits:
            memory: "128Mi"
            cpu: "250m"
        ports:
        - containerPort: 9090
        envFrom:
          - secretRef:
              name: solar-exporter
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
              - ALL
          privileged: false
          readOnlyRootFilesystem: true
          runAsNonRoot: true
          runAsUser: 1000
          runAsGroup: 1000
      - name: ssh
        image: ghcr.io/stefanabl/docker-ssh-client:20230703134245
        command: ["/bin/bash"]
        args: ["/keys/cmd.sh"]
        volumeMounts:
        - name: keys
          mountPath: "/keys"
          readOnly: true
        # livenessProbe:
        #   initialDelaySeconds: 120
        #   periodSeconds: 60
        #   timeoutSeconds: 5
        #   # use something like "curl --timeout 30 localhost:8080/status | grep 401 Unauthorized "
        #   tcpSocket:
        #     port: 8080
        resources:
          limits:
            memory: "128Mi"
            cpu: "250m"
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
              - ALL
          privileged: false
          readOnlyRootFilesystem: false
          runAsNonRoot: true
          runAsUser: 1000
          runAsGroup: 1000
      volumes:
      - name: keys
        secret:
          secretName: solar-exporter
          items:
          - key: priv-key
            path: id_rsa
          - key: pub-key
            path: id_rsa.pub
          - key: command
            path: cmd.sh
