apiVersion: apps/v1
kind: Deployment
metadata:
  name: solar-exporter
  namespace: monitoring
spec:
  selector:
    matchLabels:
      app: solar-exporter
  template:
    metadata:
      labels:
        app: solar-exporter
    spec:
      containers:
      - name: solar-exporter
        image: ghcr.io/stefanabl/solar-exporter:20240715155304
        resources:
          limits:
            memory: "128Mi"
            cpu: "250m"
        ports:
        - containerPort: 9090
        envFrom:
          - secretRef:
              name: solar-exporter
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
              - ALL
          privileged: false
          readOnlyRootFilesystem: true
          runAsNonRoot: true
          runAsUser: 1000
          runAsGroup: 1000
