apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    DOMAIN: ENC[AES256_GCM,data:RFa8+wggRpgY,iv:OlV/B7KY6OcNea5gWhx0YTvhGtK4RiJduI5Et0chhAs=,tag:Up7MCgFwvt2O0leUrnaLpQ==,type:str]
    OLD_DOMAIN: ENC[AES256_GCM,data:cFcDx/vUrrP7KZk4IV0E,iv:5/vtBWV+As2BLumbSDc3U2OhMGV4AoLCVxKEWAvq6iI=,tag:CrOQyKEY37Fal6Kr7CtwgA==,type:str]
    LOKI_MINIO_USER: ENC[AES256_GCM,data:LAISKQ==,iv:vEdLWdY3VVfxFhFpWKltYPChJ6xK4GKPdXvfQZSd5Ig=,tag:1M38p3hDfK4gUlzuXF0OWw==,type:str]
    LOKI_MINIO_PASS: ENC[AES256_GCM,data:YWZ76j5wp4M1BusHhUyuncnnv2U=,iv:y73iqNEC3224NL+yOvdQVqaQKvb8/t5YloSWwcA9hBE=,tag:+bqiLBYooYceSXe+PODeQA==,type:str]
    MINIO_PROM_TOKEN: ENC[AES256_GCM,data:kggyZGHZTqPViL0EqiCIiCH4X6g13SG9EfzdDX3MrKMy8pTefz+fEmyuSY22evcyjuD2Z7ItiojF0btA5mzw/sWBuPIdx7QhnYmJYmkggtHfP2blSG3hUNqj6Jz38mI4ZHy6ccSZC+cN7CESXa6mWd9ZT7t/Wdh55w/G31SZsgPBxeEoLOL+DlGl+Ai9sInvmUzfWCmYfQzH1Xz06zspH5FT8Da5iPn4t/aNa+UxJNlu+cRxK7T7FAJPAvwyVu0Em/f8myb1U/mZ6uubacceNxrI4PvDqVYrnbceddwh61wQuO5AeWxNnTBSF/KMWPjSD7e8W814yymXyVXw,iv:ZZH0DG331nl4fok0lttFctvVbPbpJs2G28cwqcRZXdo=,tag:5TLqKmbBhRRNjFjmIkS3mA==,type:str]
    MINO_LOKI_TOKEN: ENC[AES256_GCM,data:gzwQeBBrs9BtnuSDJY0OyAlUhGgiHW2gX9vzbA5zoIinwggEkiq8n855Rv5aTphvG6bCFlWvHHicwJjzRCFPnKa8rF0eFBGQf98R8vwl4tq9o9aI0eaBxU0xdYqK1rWAeC/xN79xBRkIm/3tM2kK2rjq+Bdl7LCMVUFhzrnrendhZVRsqDv3zo9naMPyefb8DNNt61o8bD9vSGcnN/UEWoCmgqSJGZyiSfufQ6gfH+muYqHfOWlxpwgLGt100hqxhMg8DDMC+iNjSbCU/+yn7QNp6HQ=,iv:RvPUXgMnSPCkG0LDnniAxannWBg29IX/HSCOPKyj9Ac=,tag:Fo32Sh03KrL8oUSSWdQ0dg==,type:str]
    GRAFANA_USER: ENC[AES256_GCM,data:Q/Ma0+OTtuavTig=,iv:70hWN5oVgPJw80RmnHYFDNqlQsBEQ5+24uM9u/Lm+aI=,tag:xQUwSzQCV8Q+/ibtALSzjA==,type:str]
    GRAFANA_USER_PASS: ENC[AES256_GCM,data:c1GF4IVFrMGvmNrUUPu7kZFGERdJ4U1dlJOs7Jox94pLwnjh55TA5WZ60Y+br66ZZNanzLh2GDU1CSt/vdjCv0NOhETOCaytZx8bE9QWmB3kwauclSxiutyu518f2Ek0ritflA==,iv:rFeVVuvEX+0eGDInojB/hYtlbTUpVJDKnCjKk+6x2KM=,tag:sos0JhETYLBtVZZLqcJHoA==,type:str]
    GRAFANA_OIDC_CLIENT_SECRET: ENC[AES256_GCM,data:EatzRszEVPC0eG3nderd/Xy19twsB6LkN3IddebU7V7QTkOsL3yRLXmWqFFhTvDIw0FyFl+WuwFPMG463E0pvOi3WPFKxuOWdc/qFrRNN7YWmZkaUk6IONNGyn4p2skd1UCQc7amZvLom3pgHIG7psD179WwUOQ9A83bUYg7x0M=,iv:xaPHOCcc4f7hwgQHIk6wU2HhL1FILR2OzaQCmU5pX/A=,tag:xaY2jTXBNdpW3QzTAjXAQg==,type:str]
    JELLYSEERR_OIDC_CLIENT_SECRET: ENC[AES256_GCM,data:DFm/42BuPaKCCuOjRK493Jze7E8lNjsKYF910YRZty5156KR7OvFNZagwsoeSJibw+NC2U4ErGJUK0zOFICbyvn5u/v8efTDKsuA2iErEDG+0XwXDfwQwBzuL4Oe5rCn5wrdNN6eEwkYnR9wy/iowETUJzUuoarytnY7F7MJPH4=,iv:IzGZAPh11qrbGiwsWhzhmaFiCArgZZ05bZl0qVNyQ4Y=,tag:5K9QlhGLKVxqaYCBuKb5VQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2024-05-26T22:00:25Z"
    mac: ENC[AES256_GCM,data:wQyUrqiQy14GdTsOuXpEdU1pDXxGEPq/h0VDg9Z8XZB579dzqSLKR9AQwrBvm0+j5OoRH4OQ9CKQKxAw4wSimW9eC0fWGMTyqfFJNirnv6LxQeloLW1QRBkytyWLcGxqRJmCMwLb+Ef3/oilyc7sOE7NHOmQHTjsMsZSPHl+ezw=,iv:UDjrGB3tw7ucqlvd9pZYd0OS0MWauIekg3+vunuLzL4=,tag:XG6eB1SagGZ+Jabct4ulhw==,type:str]
    pgp:
        - created_at: "2022-07-13T19:13:30Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA70fE7dz6LU0AQ/+NrMrrOh30QH6vK3jGN+4dE1YXPGkdYz/XPqPvL2+UssS
            ZsSAR+rmVARbLk+ZSaQCAaeN2iMFhTO87GCLUFfLNDuFfZZvJ68ff57xUbWkJFC4
            fI1EBZJ7wMVsV+rt9ALJ1XPMDcGF3i7+Sc7CONudtcbN2f0e29ao14nIKWyPen0J
            dBd3XndDdibd+fPW644M6wpHSBnj1OjeZMoyQui+8GtNghXy3U1L5Yo8nI0eOCvK
            1E6qWOdcUT+sjw+vjgypaR4HTsGQaI8EQCDXtnuEerfSi93RjdopyAAaL9++v47Q
            7JJkrwf8u2elaUGX/yxw3GJ32r/8Z7XuMYU8OYunDxeKRPWJEA4PEEDxzQ6nUSkk
            HNt22Dg4obv4d9jO7FrKl4JoG7cywbFEczaWsy66IRwHLfi66uCs5VF6vNdrlyXG
            9lsndKbP+Iwgvzb7snnRSO0JJiyevParuoUFsjMcTk4h8LkSW9GQThFs9OONYiDx
            mDcm2sVtOUGHV/sG0vDgWVCYdklGyOWb8mMELQoWWDknLoa8lfhVwTyFeaVVIq/e
            99wl0IL/OhXbYnjaS7Fem9lf7wQt9PVE1DYno6LHYE0k3OOQnpxQi11XkWXcWekD
            8D+Bstk+KMKJgAdNBToJJ/qUsHtICYSKRksZYK4g8QeqctFtx4M0tXYmykLYUqXS
            XgGEPmaECui53Xwtai8l+yVcNbH41Zz3KRZZ9S+0gHHKA/ecxPyeY+CU5gsDA7OC
            1OBsaNumR8xBlIwPuCycgHhayAbC5vm/zdnBGVdKuxWx73tV8MdG06S7HQyXMSM=
            =321C
            -----END PGP MESSAGE-----
          fp: 1DF23F1E7AFCAB40F26B210123CFBB30193553AA
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
