apiVersion: v1
kind: Secret
metadata:
    namespace: longhorn
    name: backup-secret
type: Opaque
stringData:
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:tAacFSJEf0U=,iv:bzfpdK/j7vHlH1lme4jm5kVJsMSLXonNnVgnmncOi6M=,tag:0+VVNvw/b77kPmlJYFK6Lg==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:vtRGhO2e4u3grXjlaKiv0uYrS7JWdkAPEpkl0F0/NXzzYB0gzWkxVg==,iv:cuoH1Gt+/1QIiam0hRQeYteL3DYusMr0SmQ1TLnasmg=,tag:EFQ0vRJ4mcYnq8Eru92PnQ==,type:str]
    AWS_ENDPOINTS: ENC[AES256_GCM,data:o7SD5q9Dp3PSCcAYLWQPmnstIrMreYX2/O4S,iv:1FSoZaX81r+sZYNzDkRV6584CDLxaMwsDI1YWxrVLw4=,tag:NeE0fwNpWQBWvfoZiurDlQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2025-02-10T20:56:57Z"
    mac: ENC[AES256_GCM,data:j8RAYotIW22dIkNQZOc/8Q7zR2JLdvv8tIeA2ufxVSCn2uL5Q+bUDsZcgSTcWhhnFsVWbfyo1eKIU0NnGNP8jHXBf18HUwl7RDLwK2LEAuACrfeqaPY3xb0V6Yt7GdKJzCISO7H7dYDZFMgcFyKqHfSmbpBGVjKNIqRy2VNRd24=,iv:52E6RMBI3BtYWeMZd9pVJIz0RZuG1iGi/5rNxUfpCYg=,tag:0soC24lFxamC6KDghRtnRg==,type:str]
    pgp:
        - created_at: "2023-08-13T10:29:59Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA70fE7dz6LU0AQ//Ru+X47SV5JztjQjOUJ2H+cZwJvu8dZXYtbMSvtmalp3a
            2la6Ja10g0fxYEWPjXly8nyTCy7WH/FP+OGD4xzLOZy2cuV1GFjjv+hzAGOPhqSQ
            Dz0mEZSFlG2Sc4B4m9u5WHv+/NfspUHSU1Gn1cnU/KUDgJqBeZwYybpeLBEI0tNY
            ZsPnzmzd2o3Y1WgA5ca1Nu334GXUtGp3Ox5yl+pnDf/80jyINIUPKe43QNGOL+n8
            vveb2XuOJn+yLb4gHZzYFGpSbInUQkyEHCAAwYuCxpoXCfZPLdAj6pTgYUhjEYzT
            hFqDjLFopy2DZ6ORKsFMwa9e5DUKC64ug4H1P7VMlIHwMHe71En5L9ZGE74ttpPQ
            P2xlImFv7m1G6c3h1mM3ojMUFQuRBNSGM9+Yan+1flJA0cBQlNrvwxWUXR1bSAqr
            89LaHj4l6JlZJPfH2sQqPIJwp0DdT4fnyCuVHTkPJkwSZm2aCAZQ7asjnjAOQBH8
            VzCZJlumdzSc41AiIk7ziVvEMo8mAhG71Ucyk8vQSG6EYGXnCJsYzpMs+Yhco6Fi
            SKKu8yl+pEvHPWav0jswCx0oiTY6gdY3soGs6g4ZKPWCj0I5TbCyQoZrXDfLfXgv
            o/ghLnQb1fMwhnWBsIIX96fhVLAbZaZkM1X4dqXlQjVdZsv+wqAb9G/ce+HhjI7S
            XgFXwRx335IzOBZZozwkBzUbDLK2HNhYdIt7khufia+N9+TSg2a8osUgYsGNzKTP
            hP+QxEryy2aVOit+fE9uoStcmPmFArOI2rx6dZWa1QhMP27airj3IxjLGKX+nUI=
            =UeFS
            -----END PGP MESSAGE-----
          fp: 1DF23F1E7AFCAB40F26B210123CFBB30193553AA
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
