apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - helm-release.yml
  - backup-secret.yml
  #- fs-trim-job.yml
  - allow-scraping.yml
  - namespace.yml
  - oauth2-proxy.yml
  - oauth2-proxy-secret.yml
  - route.yml
