apiVersion: v1
kind: Secret
metadata:
    name: oauth2-proxy
    namespace: longhorn
type: Opaque
stringData:
    #ENC[AES256_GCM,data:/h9dzPPz9KtbdChLn2TpguatIbescq83/xd9BHNcX43aBD33mf1EVxT51trMWY5duFMPAlMHIq1zjJuoukqu4RDR,iv:v7hI+rhg6hz7uI5IyoAOIqlknNcr1O7o8m12i/BVnuE=,tag:nf5BjYJVW3B9qZDTjIA/DA==,type:comment]
    #ENC[AES256_GCM,data:em1LVxv1AESOzr3g7MkKf9iYiZugvDTlhxRwXhdhNSS75SicVgt8Y7GoLqZ+IifXp+YbRk12GRq+9NVtckKVZctnguxgV1qSOHdnHb4=,iv:pjhGQ4iJrr2VD3yV1CXAeaHO2xGXW468gwS6Xpu95q4=,tag:U8lOFvTkq1xykx1dD+KehQ==,type:comment]
    #ENC[AES256_GCM,data:I7D+Y+0CpXIoF6CA2o5bcDEJyp9Tdz2FBODhnU6EBx5V5nFx2KGP2Z7hT3MIYGHKKDeKv1nYjdE+n+jZbv1kkJatcgfMdFSVJuI=,iv:XGbiE4NsWZsr2A4qUo9txugFfyvhGLRxKndEVWaYNJQ=,tag:z2xUWyi1MHjRhjL5TiBjjA==,type:comment]
    #ENC[AES256_GCM,data:LUuefdfXDjgOhiWfDPQ4NvwdjAxImNFlWqr+gCIxi2YULpDIx37C1CJQ5Ed4OUU6gtTPLfCO,iv:PSp9mZWNzJ4PW2NB4CVvHLzT6PI+z8xUjKWFBr0iLC8=,tag:bbWI5uzaBoLxrjfkPj5Y5w==,type:comment]
    #ENC[AES256_GCM,data:KRPrREKt+tvPHT9oPyNyosUSDSQIxo7N3Qj6NZx5Wz6w2rjVEqIVCJ9FH3u1OYAi3HBjhZciEuauYfWa7XeXeBSxxzm1pA==,iv:ZkNbelLo/A3CavX6gcA5RkIRtXLAs1rxhini/EBPvgg=,tag:r5P4OSRoTZZ8uJ2Zv5qg+g==,type:comment]
    OAUTH2_PROXY_CLIENT_SECRET: ENC[AES256_GCM,data:217ohCiLjd/VqtMSxudTW0LXbDAXRvJ3blKFy+qiuOxAmInWtWIHpSrqYN6V6GVRzQ==,iv:Im3JBGqp3aXR4mJtlTu230VzleWDeD9SpAI/ubGZ9/I=,tag:v0+RX4fHAR7OoC0CYOE6YQ==,type:str]
    OAUTH2_PROXY_COOKIE_SECRET: ENC[AES256_GCM,data:LFYcstFWMwzJ413VLXjzsEFSylM/9qHqRV6yKqh5w9mdWjPxv0LVEvI8OhAD7y7SIA==,iv:gOPo7hYx7QHG0u8g0zcpQiYrZChbWEFId8Rjx2o/TtQ=,tag:U0UcYRAgtLnixwjzJE4lPg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2026-08-08T13:30:53Z"
    mac: ENC[AES256_GCM,data:RAycOGyUW7ZH21YNKl2Cse3He/CmlDl1mAjLE4OhTDuw638RMxU5O7pJrSppWlu/cg2bex+ezIrrYd9gs9XbK/0eZw9KsXvSSKFd17hWKaq5C+A2A46nGSaU25t9nZkHBxKnq1p42P9P8+5OyuYN+e2w8/b9/PJ15wROOfwAVnU=,iv:LGOEt0D0+qn0MlEFp62dX6gaKlol0DMKI4auC5fS4mo=,tag:NiplclbEriITCIkb9+lMiw==,type:str]
    pgp:
        - created_at: "2026-08-08T13:30:53Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA70fE7dz6LU0AQ//bdWJ+pvMT4+ERMk1ppQ4VP+xYXUWkjoWH7fPSMTj6G6F
            sPLocFL5XrfLKtTJwwUEKb6Q4g5gw9qTMyNSHU3FiwEx6ZG8z8lhEBdV1vIocfcB
            E3xOc5sHsOMjQYJqfdlZartEQBGPagF6Mm2BLZKq4ut0u4m+5KdvMhqVDvFRiJDw
            YmERsWRD+djBs0jb+qVE6c+7tNmQf6ueiEhoGif4lKvUwD7/tXHZcS7pO1hmEDH+
            zELMCN6iw/dOH+zQlea4hfh7lB+yv1NywAQJHZuDzADtdAs7kqxQvbk0ZwE4Wyuv
            inKfqK34p5scj2Jl3Xpi8PPQaagaWUdXh0LOlluaeMfimkXCDi3odZukSYYNf59D
            0yJtFwVOocH7+38Xq3g3W1aRpnaZD5bjbevND/xOcvgTtOJ+UGt5dckbVXRmS9q+
            Vv5bKdv87cbcl9TP/rKziOnvBZX9TJoFdv+MgsvMT215gPLVF8RBBxb5Rb8p4/KY
            5T2FdQKSPkC+irVi5YozCOvkzzQsZ7mKUueItdN6f/OQKY95i+GDWWFyFpo/VdAt
            yY8pX/pWlL0m2NTRulVg8Jeka14bK3jsj5vvT8x1HKqqOvDVImEKi2qZKfyxxOZd
            28dEqnUPZCQccc8fdz9KTJ6vaIUXYKSTMlt1QSfpJ0t6wy2JN1al9Z7Agia+sffS
            XgGLeQhh2EitLL5jnTLJ2R4HOX+nP7MrsM8OJAeeRenY4t+enZxjoQkWr7KR7m/H
            2VcvAqpBhSXSdEv5MsjCRVenR28BZDWdOBQbvwYEocJInf/IgQmxmBzWCRTuGRM=
            =xtqY
            -----END PGP MESSAGE-----
          fp: 1DF23F1E7AFCAB40F26B210123CFBB30193553AA
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
