apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: redis
  namespace: documentserver
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://charts.bitnami.com/bitnami
      chart: redis
      version: 17.3.1
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
      interval: 5m
  values:
    architecture: standalone
    podAnnotations:
      container.apparmor.security.beta.kubernetes.io/redis: runtime/default
      seccomp.security.alpha.kubernetes.io/pod: runtime/default
    containerSecurityContext:
      capabilities:
        drop: ["ALL"]
      readOnlyRootFilesystem: true
      enabled: true
      runAsUser: 1001
      runAsNonRoot: true
      priviledged: false
    resources:
      limits:
        cpu: 200m
        memory: 128Mi
      requests:
        cpu: 100m
        memory: 128Mi
