apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: loki-data
  namespace: default
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20Gi
  storageClassName: longhorn