apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: minio-loki
  namespace: default
  labels:
    app: minio
spec:
  podManagementPolicy: OrderedReady
  replicas: 1
  selector:
    matchLabels:
      app: minio
  serviceName: minio-loki
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: minio
        name: minio-loki
    spec:
      initContainers:
        - name: permission-fix
          image: busybox
          command: ['sh', '-c']
          args: ['id; chown -vR 10001:10001 /data; echo done']
          securityContext:
            runAsGroup: 0
            runAsUser: 0
            runAsNonRoot: false
          volumeMounts:
            - mountPath: /data
              name: storage
      securityContext:
        fsGroup: 10001
        runAsGroup: 10001
        runAsNonRoot: true
        runAsUser: 10001
      containers:
        - name: minio
          image: minio/minio
          command: 
            - sh
          args: 
            - -c
            - 'mkdir -p /data/loki && /usr/bin/minio server /data'
          env:
            - name: MINIO_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: loki-minio-secret
                  key: access_key
            - name: MINIO_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: loki-minio-secret
                  key: secret_key
          volumeMounts:
            - name: storage
              mountPath: /data
          ports:
            - name: minio
              containerPort: 9000
              protocol: TCP
      volumes:
        - name: storage
          persistentVolumeClaim:
            claimName: loki-data