# yaml-language-server: $schema=https://json.schemastore.org/ansible-playbook
---
- hosts: k3s-0.i.stabl.one
  become: yes
  become_method: sudo
  vars_files:
   - ../../../secrets.yml
  tasks:
  - name: install required apt packages
    apt:
      name: 
        - "python3-pip"
        - "apt-transport-https"
      state: present
  - name: add key to apt
    apt_key:
      url: https://baltocdn.com/helm/signing.asc
      state: present
  - name: add apt repository
    apt_repository:
      repo: deb https://baltocdn.com/helm/stable/debian/ all main
      state: present
  - name: install helm using apt
    apt: 
      name: helm
      state: latest
  - name: install required python modules
    pip:
      name:
        - openshift
        - PyYAML
        - passlib
  - name: add Grafana helm repo
    community.kubernetes.helm_repository:
      name: grafana
      url: https://grafana.github.io/helm-charts
  - name: install helm diff
    kubernetes.core.helm_plugin:
      plugin_path: https://github.com/databus23/helm-diff
      state: present




  - name: Create PVC
    community.kubernetes.k8s:
      kubeconfig: /etc/rancher/k3s/k3s.yaml
      state: present
      definition: "{{ lookup('file', 'loki-pvc.yml') | from_yaml }}"

  - name: Create Minio secret
    community.kubernetes.k8s:
      kubeconfig: /etc/rancher/k3s/k3s.yaml
      state: present
      apply: yes
      definition: 
        apiVersion: v1
        kind: Secret
        metadata:
          namespace: default
          name: loki-minio-secret
        type: Opaque
        stringData:
          access_key: "{{logging.loki.minio.access_key}}"
          secret_key: "{{logging.loki.minio.secret_key}}"
  - name: create minio stateful set
    community.kubernetes.k8s:
      kubeconfig: /etc/rancher/k3s/k3s.yaml
      state: present
      apply: yes
      definition: "{{ lookup('file', 'minio-statefulset.yml') | from_yaml_all | list }}"
  - name: create minio service
    community.kubernetes.k8s:
      kubeconfig: /etc/rancher/k3s/k3s.yaml
      state: present
      apply: yes
      definition: "{{ lookup('file', 'minio-service.yml') | from_yaml }}"

  - name: template values file
    template:
      src: values.yml
      dest: /root/loki-distributed-values.yml
    changed_when: false

  - name: install helm chart
    community.kubernetes.helm:
      kubeconfig: /etc/rancher/k3s/k3s.yaml
      update_repo_cache: yes
      name: loki
      chart_ref: grafana/loki-distributed
      release_namespace: default
      values_files:
        - /root/loki-distributed-values.yml
    register: helmout

  - debug:
      var: helmout
  
  - name: Create basic auth file
    community.general.htpasswd:
      path: /root/.passwordfile
      name: "{{item.name}}"
      password: "{{item.password}}"
    with_items: "{{logging.loki.users}}"
    changed_when: false
  - name: Read password file
    shell: cat /root/.passwordfile
    register: passwords
    changed_when: false

  - name: Create Basic Auth Secret
    community.kubernetes.k8s:
      kubeconfig: /etc/rancher/k3s/k3s.yaml
      state: present
      definition:
        apiVersion: v1
        kind: Secret
        metadata:
          namespace: default
          name: lokiauth
        type: Opaque
        data:
          auth: "{{passwords.stdout | b64encode }}"
    register: secret

  - name: Create Ingress
    community.kubernetes.k8s:
      kubeconfig: /etc/rancher/k3s/k3s.yaml
      state: present
      definition: "{{ lookup('file', 'loki-ingress.yml') | from_yaml }}"
  - name: Delete temporary files
    file:
      path: "{{item}}"
      state: absent
    with_items:
      - /root/.passwordfile
      - /root/loki-distributed-values.yml
    changed_when: false
    when: true
