ingester:
  replicas: 3
  podAnnotations: 
    container.apparmor.security.beta.kubernetes.io/loki: runtime/default
  resources:  
    limits:
      cpu: 250m
      memory: 300Mi
    requests:
      cpu: 50m
      memory: 100Mi
querier:
  podAnnotations: 
    container.apparmor.security.beta.kubernetes.io/loki: runtime/default
  replicas: 3
  resources:  
    limits:
      cpu: 2
      memory: 2048Mi
    requests:
      cpu: 50m
      memory: 300Mi
distributor:
  podAnnotations: 
    container.apparmor.security.beta.kubernetes.io/loki: runtime/default
  resources:  
    limits:
      cpu: 250m
      memory: 300Mi
    requests:
      cpu: 50m
      memory: 100Mi
queryFrontend:
  podAnnotations: 
    container.apparmor.security.beta.kubernetes.io/loki: runtime/default
  resources:  
    limits:
      cpu: 250m
      memory: 300Mi
    requests:
      cpu: 50m
      memory: 100Mi
gateway:
  podAnnotations: 
    container.apparmor.security.beta.kubernetes.io/nginx: runtime/default
  resources:  
    limits:
      cpu: 250m
      memory: 300Mi
    requests:
      cpu: 50m
      memory: 50Mi
  nginxConfig:
    httpSnippet: |
      proxy_read_timeout 600s;
      proxy_connect_timeout 600s;
      proxy_send_timeout 600s;
      send_timeout 600s;


loki:
  containerSecurityContext:
    readOnlyRootFilesystem: true
    capabilities:
      drop:
        - ALL
    allowPrivilegeEscalation: false
    privileged: false
  podAnnotations: 
    seccomp.security.alpha.kubernetes.io/pod: runtime/default
  config: |
    auth_enabled: false

    server:
      log_level: info #TODO: REDUCE
      # Must be set to 3100
      http_listen_port: 3100
      http_server_read_timeout: 15m
      http_server_write_timeout: 15m

    distributor:
      ring:
        kvstore:
          store: memberlist

    ingester:
      # Disable chunk transfer which is not possible with statefulsets
      # and unnecessary for boltdb-shipper
      max_transfer_retries: 0
      chunk_idle_period: 1h
      chunk_target_size: 1536000
      max_chunk_age: 1h
      lifecycler:
        join_after: 0s
        ring:
          kvstore:
            store: memberlist
      wal:
        dir: /var/loki/wal
    querier:
      query_timeout: 15m
      engine:
        timeout: 15m
    memberlist:
      join_members:
        - {% raw %}{{ include "loki.fullname" . }}-memberlist{% endraw %}
        #Empty line needed after endraw

    limits_config:
      ingestion_rate_mb: 10
      ingestion_burst_size_mb: 20
      max_concurrent_tail_requests: 20
      max_cache_freshness_per_query: 10m

    schema_config:
      configs:
        - from: 2020-09-07
          store: boltdb-shipper
          object_store: aws
          schema: v11
          index:
            prefix: loki_index_
            period: 24h

    storage_config:
      aws:
        s3: https://{{logging.loki.minio.access_key}}:{{logging.loki.minio.secret_key}}@s3.{{internal_domain}}.:9000/loki
        s3forcepathstyle: true
      boltdb_shipper:
        active_index_directory: /var/loki/index
        shared_store: s3
        cache_location: /var/loki/cache

    query_range:
      # make queries more cache-able by aligning them with their step intervals
      align_queries_with_step: true
      max_retries: 5
      # parallelize queries in 15min intervals
      split_queries_by_interval: 15m
      cache_results: true

      results_cache:
        cache:
          enable_fifocache: true
          fifocache:
            max_size_items: 1024
            validity: 24h
    frontend_worker:
      frontend_address: {% raw %}{{ include "loki.queryFrontendFullname" . }}:9095{% endraw %}
      #Empty line needed after endraw

    frontend:
      log_queries_longer_than: 5s
      compress_responses: true

