apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - poller-deploy.yml
  - poller-secret.yml
  - poller-svc.yml
configMapGenerator:
  - name: unifi-poller
    namespace: monitoring
    files:
    - poller.conf
