apiVersion: apps/v1
kind: Deployment
metadata:
  name: unifi-poller
  namespace: monitoring
  # annotations:
spec:
  selector:
    matchLabels:
      app: unifi-poller
  template:
    metadata:
      labels:
        app: unifi-poller
      annotations:
        container.apparmor.security.beta.kubernetes.io/unifi-poller: runtime/default
        seccomp.security.alpha.kubernetes.io/pod: runtime/default
        reloader.stakater.com/auto: "true"
    spec:
      containers:
        - name: unifi-poller
          image: golift/unifi-poller:v2.11.2
          args:
            - -c
            - /config/poller.conf
          resources:
            requests:
              memory: "64Mi"
              cpu: "50m"
            limits:
              memory: "128Mi"
              cpu: "250m"
          ports:
            - containerPort: 9130
              name: prom
          volumeMounts:
            - name: config
              mountPath: /config/
            - name: creds
              mountPath: /etc/creds/
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            privileged: false
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            runAsUser: 1000
            runAsGroup: 1000
      volumes:
        - name: config
          configMap:
            name: unifi-poller
            items:
              - key: "poller.conf"
                path: poller.conf
        - name: creds
          secret:
            secretName: unifi-poller
            items:
              - key: password
                path: passwd.file
      automountServiceAccountToken: false
  strategy: {}
