---

- ansible.posix.sysctl:
    name: fs.inotify.max_user_watches
    value: '100000'
    state: present
- ansible.posix.sysctl:
    name: fs.inotify.max_user_instances
    value: '1024'
    state: present

- include: addons.yml
  tags:
  - addons

- name: k3s | cluster configuration
  include_role:
    name: xanmanning.k3s
    public: yes

- include: cleanup.yml
  tags:
  - cleanup

- include: kubeconfig.yml
  tags:
  - kubeconfig
