kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: allow-to-nextcloud
spec:
  policyTypes:
  - Egress
  podSelector: {}
  egress:
  - to:
    - ipBlock:
        cidr: 10.13.2.101/32
    ports:
    - protocol: TCP
      port: 443
