# yaml-language-server: $schema=https://json.schemastore.org/ansible-playbook
---
- hosts: nextcloud.i.stabl.one
  become: yes
  become_method: sudo
  vars_files:
   - ../../../secrets.yml
  tasks:
  - name: Download promtail
    get_url:
      url: https://github.com/grafana/loki/releases/download/v2.1.0/promtail-linux-amd64.zip
      dest: /tmp/promtail.zip
  - name: unzip promtail
    unarchive:
      src: /tmp/promtail.zip
      dest: /usr/local/bin/
      mode: "0755"
      remote_src: true
  - name: Template promtail configuration
    template:
      src: promtail.yml
      dest: /etc/
    vars:
      username: nextcloud
      
  - name: template systemd service file
    template: 
      src: promtail.service
      dest: /etc/systemd/system/
  - name: start promtail
    systemd: 
      state: restarted 
      name: promtail 
      daemon_reload: yes
      