---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: node-feature-discovery
  namespace: kube-system
spec:
  interval: 15m
  chart:
    spec:
      # renovate: registryUrl=https://kubernetes-sigs.github.io/node-feature-discovery/charts
      chart: node-feature-discovery
      version: 0.15.3
      sourceRef:
        kind: HelmRepository
        name: node-feature-discovery-charts
        namespace: flux-system
  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  values:
    nodeFeatureRule:
      createCRD: true
    worker:
      annotations:
        configmap.reloader.stakater.com/reload: node-feature-discovery-worker-conf
      config:
        core:
          sources:
            - pci
