- file:
    path: ~/dovecot
    state: directory
- template:
    src: "{{item}}"
    dest: ~/dovecot/
  with_items:
    - "Dockerfile"
    - "start.sh"
- shell: "cd ~/dovecot/ && docker build -t dovecot . && rm * && cd .. && rmdir dovecot"
- file:
    path: "{{item}}"
    state: directory
    owner: "{{mailserver_bindUser}}"
    group: "{{mailserver_bindUser}}"
    mode: 0700
  with_items:
    - "{{docker_dir}}/dovecot/config/conf.d"
    - "{{docker_dir}}/dovecot/config/sieve-before.d"
    - "{{docker_dir}}/mail/vhosts"
    - "{{docker_dir}}/mail/attachments"

- name: template conf.d directory
  template:
    src: "{{ item }}"
    dest: "{{docker_dir}}/dovecot/config/conf.d/"
    owner: "{{mailserver_bindUser}}"
    group: "{{mailserver_bindUser}}"
    mode: 0600
  with_fileglob:
    - conf.d/*
- name: template sieve-before.d directory
  template:
    src: "{{ item }}"
    dest: "{{docker_dir}}/dovecot/config/sieve-before.d/"
    owner: "{{mailserver_bindUser}}"
    group: "{{mailserver_bindUser}}"
    mode: 0600
  with_fileglob:
    - sieve-before.d/*
- name: Precompile sieve scripts
  docker_container:
    image: dovecot
    name: sieve-compiler
    auto_remove: true
    sysctls: "net.ipv6.conf.all.disable_ipv6=0"
    etc_hosts:
      "{{mailserver_replica_name}}={{replica_container_primary_ip.stdout}}"
    volumes:
      - "{{docker_dir}}/dovecot/config:/config"
      - "/etc/ipa/ca.crt:/etc/ipa/ca.crt:ro"
    entrypoint: "/bin/sh"
    command:
     - sh
     - -c
     - sievec /config/sieve-before.d/*
- name: template ldap.conf.ext and dovecot.conf
  template:
    src: "{{item}}"
    dest: "{{docker_dir}}/dovecot/config"
    owner: "{{mailserver_bindUser}}"
    group: "{{mailserver_bindUser}}"
    mode: 0600
  with_items:
    - ldap.conf.ext
    - dovecot.conf



- docker_container:
    name: dovecot
    image: dovecot
    state: started
    detach: true
    recreate: true
    restart_policy: always
    sysctls: "net.ipv6.conf.all.disable_ipv6=0"
    etc_hosts:
      "{{mailserver_replica_name}}={{replica_container_primary_ip.stdout}}"
    networks:
      - name: primary
    published_ports:
      - "993:993"
    volumes:
      - "{{docker_dir}}/dovecot/config:/config"
      - "/etc/ipa/ca.crt:/etc/ipa/ca.crt:ro"
      - "{{docker_dir}}/mail:/data"
    hostname: "mail.{{domain_name}}"
    dns_servers:
      - "{{ipa_server_ip}}"
      - "1.1.1.1"
      - "8.8.8.8"
    log_driver: json-file
    log_options:
      tag: "{% raw %}{{.ImageName}}|{{.Name}}|{{.ImageFullID}}|{{.FullID}}{% endraw %}"
