apiVersion: apps/v1
kind: Deployment
metadata:
  name: mobivey-be
  namespace: mobivey
  labels:
    app: mobivey-be
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mobivey-be
  template:
    metadata:
      name: mobivey-be
      labels:
        app: mobivey-be
        allow: db
    spec:
      imagePullSecrets:
        - name: image-pull-creds
      containers:
        - name: mobivey-be
          image: ghcr.io/stefanabl/motionmapper-backend:20250513092650
          imagePullPolicy: IfNotPresent
          env:
            - name: CORS_ORIGIN
              value: "https://app.mobivey.de"
            - name: PORT
              value: "8200"
            - name: DB_HOST
              value: "cluster.db.svc.cluster.local"
            - name: DB_PORT
              value: "3306"
            - name: DB_USER
              value: "mobivey"
            - name: DB_NAME
              value: "mobivey"
            - name: DB_PASS
              valueFrom:
                secretKeyRef:
                  name: mobivey
                  key: MYSQL_ROOT_PASSWORD
          ports:
            - containerPort: 8200
              protocol: TCP
      restartPolicy: Always
