apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: mobivey
resources:
  - frontend/fe-deployment.yaml
  - frontend/fe-service.yaml
  - frontend/fe-ingress.yaml
  - frontend/image-policy.yml
  - frontend/image-repository.yml
  - frontend/image-automation.yml

  - be-deployment.yaml
  - be-service.yaml
  - be-ingress.yaml
  - image-pull-creds.yaml
  - secret.yaml
  - allow-to-mobivey-ns.yml
  - ../../policies/allow-from-ingress.yml
  - ../../policies/allow-to-dns.yml
  - ../../policies/allow-to-internet.yml
  - ../../policies/allow-from-external-ingress.yml
  - ../../policies/allow-to-db.yml
