apiVersion: v1
kind: Secret
metadata:
    name: mobivey
    namespace: mobivey
stringData:
    MYSQL_ROOT_PASSWORD: ENC[AES256_GCM,data:835RJ1bDtZxnp06w8Dppa0RbhqSH3Bz6WDCOMugfHRTXHXJlDUPmf7NdzMeOlcKYlrs=,iv:jLGpxL7Jen+pZixxgPPAk2UZ1ID1vP8VKOgQ9RHOQSU=,tag:e6N2FjbtKOcJEO4IkpTYNA==,type:str]
#WARNING: You should not place the username and password in the version control repository or anywhere else in plain text.
#Instead, use the Services Tool Window -> Kubernetes -> <Desired Cluster> -> Configuration -> <right-click on Secrets> -> Create New Secret...
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2025-01-12T14:53:40Z"
    mac: ENC[AES256_GCM,data:M1mW0s45D08w/hNv9h//PWtcJiUNHqYmUFK/hS1nlNzJkKI5qOg4u/l9Y7N7EtRSm+6naukiAVY9wX+cWtcesCybqOf9J3vkrEZ/SRDKfSC7c9faTJ7nZGcGDC7Q9DG21Cv2+AFMNY40gB3aHgaBW/4vbX1bNkw+bSRyzIwUNCw=,iv:usUQKt/sgaFo2vvJbTUvJ4j4wLTyAhYpmKCrMR94dpQ=,tag:juiUOjSchyBIOIewcCWcpA==,type:str]
    pgp:
        - created_at: "2025-01-12T14:53:40Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA70fE7dz6LU0ARAAigOkaqa0MXGyocV6NnpRmUKXhdBgduXdFUye1xhnFGP1
            zsYGp+bV6AP8iys2SkOwoLd/DX5Rqj9s3GBvMDAkSc9LiL9SY+qOtPJklvRC/AqQ
            ATWNPNNLHmA/9Sf4njDHvUmRNFSoeKsop+J0fJ2aX4aRHTGexqO5GXYA2FSNBmR5
            ysmquGjIE0CbacVelRxrX5F4VIbjvLN1CoE8ZI4kFv2D3Y2k+P66iotAc6PjUF7K
            Zy0WLZPAs4AzLbFnXBBP9dKUqXHBTb+z5UB1azlL1SCMvJp5kXAM3dNfVj7zFUjf
            HpM+aWtRHwIvGahvG04IW1o1/BT9lVIGykBqVN3SXtzu7VHqqfJXfRq21je3ajNJ
            f7EhJAkxy8qN0gV7zToYxxOX61oJyM4scKoCexe7NXUR4+a4eRGDQ4QRSEiTSkBN
            ud4lZJ7fYmFURLmowQ+ZGWS9p6tRoyCA/WJ2MvVv9smfJrbfeNzv2jcC4bT3Bmja
            rrwPER4DMGFUu+tWXJxEh0iTUd8tAdeZSvqYo+NPXCd1zxfVTHvKB/rSR2/yvJ0w
            zq1Z2Y2K8TR6tdIz0X4LCXYXhOtxhhJgJDrt+DmcDdclWxV4iLRycG/D+M66150m
            qBtZTOZZx++8/VaJOW7r926YJSojK7aMrsUU5yxcopBchaHu/iSZawfWXpBIIBzS
            XgHF6vuP7XoZuDBJCbrWhMXxv2jTIJjIBxnOOLGDsgYXmJSWvFUAmU0EAvekiIG3
            cte9YNtwFuefLCsxgebWXNvwaPp0WrWsh7KMRiCkzzsU9/h3WrUuU89QW4DnrlI=
            =xy3t
            -----END PGP MESSAGE-----
          fp: 1DF23F1E7AFCAB40F26B210123CFBB30193553AA
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
