- name: create portainer volume
  docker_volume:
    name: portainer_data
  become: yes
- name: create container
  become: yes
  docker_container:
    name: portainer
    image: "portainer/portainer"
    state: started
    detach: true
    recreate: "{{recreate}}"
    restart_policy: unless-stopped
    networks:
      - name: primary
    published_ports:
      - "127.0.0.1:9000:9000"
    volumes:
      - "portainer_data:/data"
      - "/var/run/docker.sock:/var/run/docker.sock"
    command: "-H unix:///var/run/docker.sock"
