apiVersion: k8s.mariadb.com/v1alpha1
kind: MariaDB
metadata:
  name: mariadb-galera
  namespace: db
spec:
  rootPasswordSecretKeyRef:
    name: galera-cluster-root
    key: root-password

  replicas: 3
  storage:
    size: 16Gi
    storageClassName: local-path

  galera:
    enabled: true
