apiVersion: k8s.mariadb.com/v1alpha1
kind: MariaDB
metadata:
  name: cluster
  namespace: db
spec:
  rootPasswordSecretKeyRef:
    name: galera-cluster-root
    key: root-password

  replicas: 3
  storage:
    size: 16Gi
    storageClassName: local-path
  updateStrategy:
    type: ReplicasFirstPrimaryLast
    autoUpdateDataPlane: true
  galera:
    enabled: true
    # recovery:
      # forceClusterBootstrapInPod: "cluster-1"
    config:
      volumeClaimTemplate:
        storageClassName: local-path
        resources:
          requests:
            storage: 100Mi
        accessModes:
          - ReadWriteOnce
  # Tune your liveness probe accordingly to avoid Pod restarts.
  livenessProbe:
    periodSeconds: 10
    timeoutSeconds: 5

  # Tune your readiness probe accordingly to prevent disruptions in network traffic.
  readinessProbe:
    periodSeconds: 10
    timeoutSeconds: 5

  # Tune your startup probe accordingly to ensure that the SST completes with a large amount of data.
  # failureThreshold × periodSeconds = 30 × 30 = 900s = 15m until the container gets restarted if unhealthy
  startupProbe:
    failureThreshold: 30
    periodSeconds: 30
    timeoutSeconds: 5
