apiVersion: k8s.mariadb.com/v1alpha1
kind: MariaDB
metadata:
  name: cluster
  namespace: db
spec:
  rootPasswordSecretKeyRef:
    name: galera-cluster-root
    key: root-password

  replicas: 3
  storage:
    size: 16Gi
    storageClassName: local-path

  galera:
    enabled: true
    config:
      volumeClaimTemplate:
        storageClassName: local-path
        resources:
          requests:
            storage: 100Mi
        accessModes:
          - ReadWriteOnce
  podSecurityContext:
    runAsUser: 0
