apiVersion: v1
kind: Secret
metadata:
    name: s3-user
    namespace: db
stringData:
    username: ENC[AES256_GCM,data:sGJaNyWG+fYtU+07pKfBseuEpzjDBw==,iv:gqhmXDxVMD+nKdxsuCQfZqbpsETT+5KCAHk6su4Mo+U=,tag:ZJ+t1KwHjs3MGbejBluKzg==,type:str]
    secret: ENC[AES256_GCM,data:78FXrSsaoNy96BV6bzJMCCeUQK2lKsGjqIisoWG3zpZ34CSg1QU84n6gZ9k4UuuOr0w=,iv:gYZ1cuMkuuNj78ybWNkGq4oieWa54dwY7Mj7EbesCaA=,tag:c5g40gjeE2eTrirVtdRhag==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2025-04-29T07:55:39Z"
    mac: ENC[AES256_GCM,data:4HauC6QfH5v21iqzP+nHKb4ac801JCfso+teM+Ey7SYVXOQCqSllA1M46jS3D3yKv/XYw4BtHg+SYJVODX1C2m7GxKX4HRxPiqf8RQ1kHBcIc9tnfjoL6DR1kC42efhQ8cYYo8+hcfqwYimpAQXpNPgRwwpFx12xvGkCLimFO/I=,iv:ZGoeprIksOdUEBM+8iwLYWN2xtPf+OjyejfXkV1NojQ=,tag:TNlqrumBn3KVTyO1zog98Q==,type:str]
    pgp:
        - created_at: "2025-04-29T07:55:39Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA70fE7dz6LU0AQ//f/uCPUv14q/2RihG+xtd38qhZ2NlGNXxBurDFpgd59Kz
            rMfGYxPvYXf6KikqOy1/jxBhC0kZpP7JclwSW5TR+R4fOghiPNt73YOeA/qpLqKY
            0NaP3tDM8OQ57id6UdhKGBFl/TsczFQJNOyGJCgnDxU3xNE5fMpl19Z4utClfS7F
            JsaaTJkCHtLrVmKLbBFMTUC+3g3f32HAdNQN8mR90qnvIn0BZltM/Ogjj4rc1QST
            USFvf+zXyVw1bdIKmxL0XM1ZQli1mZmLUXiFeniRlsTFqVs3P1RA45Xlkrt3aeVf
            kjPMCIQ4EEyEzVAmbvnX4yp9ZODGcMOZbnGsWbqPF++siIorq7v5iXgmUZ2ZT50T
            eTdkKp2utDnDxuNf73rHmtDNZHtdW2oOH9Jt3XzofPYnyqs14m1+vvEY7V0gflYL
            IPOVEdQXmZkdP+5uJTWoMEvagtgLR8QWGou1g8/YCXbkv55PgAEbyIrzCWB7GGju
            9DJHQOpQIip6+yFwK55A6DwIHrnzih+qcsVeGA92O5NtJUi/1xeq3ANqdC73eH92
            zZhum9IJQz9jRzc3QKMc8G0G34bMKHWRYkR0lN6W89ZLOuBAbQoD9UBz4Qf8ex/H
            Tge3p6Iv3MFce6CqcHyRkujZsb+lMkWMruFgqsthEfdukrl30eXo4SEvqMiGNMXS
            XgG2oEvFJvcpYP/HCx2IrvkbBwa+eeIZZ2BOdZA3EZ61SZuUJ6Y0RKC4HzCjB8dP
            bvEl2RGgNRPaDcASlw18ocNPibXNaqEz3Os/H3p5Q7MDOHUpnhABNnnUTKqiWWs=
            =b/yl
            -----END PGP MESSAGE-----
          fp: 1DF23F1E7AFCAB40F26B210123CFBB30193553AA
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
