apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: influxdb2
  namespace: monitoring
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://helm.influxdata.com/
      chart: influxdb2
      version: 2.1.1
      sourceRef:
        kind: HelmRepository
        name: influxdata
        namespace: flux-system
      interval: 5m
  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  values:
    persistence:
      enabled: true
      useExisting: true
      name: influxdb2-longhorn
    ingress:
      enabled: true
      className: nginx
      hostname: influxdb2.k3s.i.${DOMAIN}
      tls: true
      secretName: influxdb2-cert
      annotations:
        kubernetes.io/ingress.class: nginx
        cert-manager.io/issuer: freeipa-issuer
        cert-manager.io/issuer-group: certmanager.freeipa.org
        cert-manager.io/issuer-kind: ClusterIssuer
        cert-manager.io/common-name: influxdb2.k3s.i.${DOMAIN}
        nignx.ingress.kubernetes.io/force-ssl-redirect: "true"
    resources:
      limits:
        memory: 1024Mi
      requests:
        cpu: 125m
        memory: 250Mi

    # Security
    podAnnotations:
      container.apparmor.security.beta.kubernetes.io/influxdb2: runtime/default
      seccomp.security.alpha.kubernetes.io/pod: runtime/default

    securityContext:
      privileged: false
      allowPrivilegeEscalation: false
      runAsNonRoot: true
      runAsUser: 1000
      runAsGroup: 1000
      capabilities:
        drop:
          -  ALL
