apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: influxdb2-longhorn
  namespace: monitoring
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  storageClassName: longhorn
  volumeName: influxdb-2
