apiVersion: certmanager.freeipa.org/v1beta1
kind: ClusterIssuer #so that all namespaces can use it
metadata:
  name: freeipa-issuer
spec:
  host: ipa.i.stabl.one
  user:
    namespace: freeipa-issuer-system
    name: freeipa-auth
    key: user
  password:
    namespace: freeipa-issuer-system
    name: freeipa-auth
    key: password

  # Optionals
  serviceName: HTTP
  addHost: false
  addService: true
  addPrincipal: true
  ca: ipa
  #Do not check certificate of IPA server
  insecure: true
  #This fixes a bug when adding a service
  #ignoreError: true
