version: '2'

services:
  db:
    image: mariadb:10.5
    restart: always
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    volumes:
      - /nextcloud_local/db:/var/lib/mysql
      - /nextcloud_local/secrets/nextcloud_maridb_root_password:/run/secrets/nextcloud_maridb_root_password:ro
      - /nextcloud_local/secrets/nextcloud_db_user_pass:/run/secrets/nextcloud_db_user_pass:ro
      - /nextcloud_local/dbdump/dbBackup.sql:/docker-entrypoint-initdb.d/dbBackup.sql:ro
      - /nextcloud_local/db_config:/etc/mysql/conf.d:ro
    environment:
      - MARIADB_ROOT_PASSWORD_FILE=/run/secrets/nextcloud_maridb_root_password
      - MARIADB_PASSWORD_FILE=/run/secrets/nextcloud_db_user_pass
      - MYSQL_DATABASE=owncloud
      - MYSQL_USER=owncloud
    logging:
      driver: json-file
      options:
        tag: "{% raw %}{{.ImageName}}|{{.Name}}|{{.ImageFullID}}|{{.FullID}}{% endraw %}"


  redis:
    image: "redis:alpine"
    restart: always
    command: redis-server
    logging:
      driver: json-file
      options:
        tag: "{% raw %}{{.ImageName}}|{{.Name}}|{{.ImageFullID}}|{{.FullID}}{% endraw %}"


  app:
    build: ./nextcloud
    restart: always
    links:
      - db
    volumes:
      - /nextcloud_local/webroot:/var/www/html
      - /data:/data
      - /etc/ssl/certs/:/etc/ssl/certs:ro
      - /nextcloud_local/php-config/php-config.conf:/usr/local/etc/php-fpm.d/zz-custom.conf:ro
    depends_on:
      - db
      - redis
    logging:
      driver: json-file
      options:
        tag: "{% raw %}{{.ImageName}}|{{.Name}}|{{.ImageFullID}}|{{.FullID}}{% endraw %}"


  web:
    image: nginx
    restart: always
    ports:
      - 80:80
      - 443:443
    links:
      - app
    volumes:
      - /nextcloud_local/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - /nextcloud_local/nginx/certs:/etc/nginx/certs:ro
      - /nextcloud_local/webroot:/var/www/html:ro
    volumes_from:
      - app
    logging:
      driver: json-file
      options:
        tag: "{% raw %}{{.ImageName}}|{{.Name}}|{{.ImageFullID}}|{{.FullID}}{% endraw %}"


  cron:
    build: ./cron
    restart: always
    volumes:
      - /nextcloud_local/webroot:/var/www/html
      - /data:/data
      - /etc/ssl/certs/:/etc/ssl/certs:ro
    entrypoint: /cron.sh
    depends_on:
      - db
      - redis
    logging:
      driver: json-file
      options:
        tag: "{% raw %}{{.ImageName}}|{{.Name}}|{{.ImageFullID}}|{{.FullID}}{% endraw %}"


  backup:
    build: ./backup
    restart: always
    volumes:
      - /nextcloud_local/webroot:/var/www/html:ro
      - /data:/data
      - /nextcloud_local/secrets/nextcloud_db_user_pass:/run/secrets/nextcloud_db_user_pass:ro
    entrypoint: /cron.sh
    depends_on:
      - db
    logging:
      driver: json-file
      options:
        tag: "{% raw %}{{.ImageName}}|{{.Name}}|{{.ImageFullID}}|{{.FullID}}{% endraw %}"


  logs:
    image: grafana/promtail
    restart: always
    command: -config.file /etc/promtail.yml
    user: "33"
    group_add:
      - www-data
    volumes:
      - /data:/data:ro
      - /nextcloud_local/promtail/promtail.yml:/etc/promtail.yml:ro
      - /nextcloud_local/promtail/positions:/var/promtail/positions
      - /etc/ssl/certs/:/etc/ssl/certs:ro
    logging:
      driver: json-file
      options:
        tag: "{% raw %}{{.ImageName}}|{{.Name}}|{{.ImageFullID}}|{{.FullID}}{% endraw %}"
