apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: s3gw
  namespace: monitoring
spec:
  selector:
    matchLabels:
      app: s3gw
  serviceName: s3gw
  replicas: 1
  template:
    metadata:
      labels:
        app: s3gw
    spec:
      containers:
      - name: s3gw
        image: quay.io/s3gw/s3gw:v0.23.1
        env:
        - name: RGW_DEFAULT_USER_ACCESS_KEY
          value: ${LOKI_MINIO_USER}
        - name: RGW_DEFAULT_USER_SECRET_KEY
          value: ${LOKI_MINIO_PASS}
        ports:
        - containerPort: 7480
          name: s3
        volumeMounts:
        - name: s3
          mountPath: /data
  volumeClaimTemplates:
  - metadata:
      name: s3
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 40Gi
      storageClassName: longhorn
