apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ingress-nginx
  namespace: ingress-nginx
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://kubernetes.github.io/ingress-nginx
      chart: ingress-nginx
      version: 4.8.4
      sourceRef:
        kind: HelmRepository
        name: ingress-nginx
        namespace: flux-system
      interval: 5m
  values:
    controller:
      allowSnippetAnnotations: true
      config:
        use-forwarded-headers: true # TODO remove when exposing directly to the internet
      admissionWebhooks:
        enabled: false
    udp:
      "3478": "default/unifi:3478"
    tcp:
      "8080": "default/unifi:8080"
