apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ingress-nginx
  namespace: ingress-nginx
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://kubernetes.github.io/ingress-nginx
      chart: ingress-nginx
      version: 4.14.3
      sourceRef:
        kind: HelmRepository
        name: ingress-nginx
        namespace: flux-system
      interval: 5m
  values:
    controller:
      replicaCount: 3
      allowSnippetAnnotations: true
      config:
        #allow-snippet-annotations: true
        use-forwarded-headers: true # TODO remove when exposing directly to the internet
        annotations-risk-level: Critical
      admissionWebhooks:
        enabled: false
    udp:
      "3478": "default/unifi:3478"
      "53": "default/coredns:53"
    tcp:
      "8080": "default/unifi:8080"
