apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: syncserver
  namespace: ffsync
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: longhorn
