apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: syncserver
  namespace: ffsync
spec:
  selector:
    matchLabels:
      app: syncserver
  serviceName: syncserver
  replicas: 1
  template:
    metadata:
      labels:
        app: syncserver
      annotations:
        container.apparmor.security.beta.kubernetes.io/syncserver: runtime/default
        seccomp.security.alpha.kubernetes.io/pod: runtime/default
    spec:
      securityContext:
        runAsUser: 1001
        runAsGroup: 1001
      containers:
        - name: syncserver
          image: mozilla/syncserver:latest
          env:
            - name: SYNCSERVER_PUBLIC_URL
              value: https://ffsync.${OLD_DOMAIN}
            - name: SYNCSERVER_SQLURI
              value: sqlite:////data/syncserver.db
            - name: SYNCSERVER_BATCH_UPLOAD_ENABLED
              value: "true"
            - name: SYNCSERVER_FORCE_WSGI_ENVIRON
              value: "true"
            - name: SYNCSERVER_FORWARDED_ALLOW_IPS
              value: "*"
            - name: SYNCSERVER_DEBUG_ENABLED
              value: "true"
            - name: PORT
              value: "5001"
            - name: SYNCSERVER_SECRET
              valueFrom:
                secretKeyRef:
                  name: syncserver
                  key: token
          ports:
            - containerPort: 5001
              name: web
          volumeMounts:
            - name: db
              mountPath: /data
            - name: tmp
              mountPath: /tmp
          resources:
            requests:
              memory: 100Mi
              cpu: 50m
            limits:
              memory: 400Mi
              cpu: 500m
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            privileged: false
            readOnlyRootFilesystem: true
            runAsNonRoot: true
      volumes:
        - name: tmp
          emptyDir: {}
        - name: db
          persistentVolumeClaim:
            claimName: syncserver
      automountServiceAccountToken: false
  updateStrategy: {}
