# needs variables server_name(host name), upstream (Web address), record(String), protected (Boolean)
  - debug:
      var: domain
  - name: create nginx config directories
    become_user: "{{user}}"
    file:
      path: "{{ item }}"
      state: directory
    with_items:
      - "{{ nginx_config_dir }}"
      - "{{ nginx_sites_dir }}"

  - name: template nginx.conf
    become_user: "{{user}}"
    template:
      src: nginx.conf
      dest: "{{ nginx_config_dir }}"
  - name: template files
    become_user: "{{user}}"
    template:
      src: "{{ item }}"
      dest: "{{ nginx_sites_dir }}"
    with_items:
      - auth.conf
      - authelia.conf
      - proxy.conf
