apiVersion: apps/v1
kind: Deployment
metadata:
  name: nc-exporter
  namespace: default
  annotations:
    keel.sh/policy: "major"
    keel.sh/trigger: poll     # enable active repository checking
    keel.sh/approvals: "1"    # required approvals to update  annotations:
    keel.sh/pollSchedule: "@every 10m"
spec:
  selector:
    matchLabels:
      app: nc-exporter
  template:
    metadata:
      labels:
        app: nc-exporter
      annotations:
        container.apparmor.security.beta.kubernetes.io/nc-exporter: runtime/default
        seccomp.security.alpha.kubernetes.io/pod: runtime/default
    spec:
      containers:
        - name: nc-exporter
          image: xperimental/nextcloud-exporter:0.5.1
          args:
            - "--server"
            - "https://cloud.{{domain_name}}"
          env:
            - name: NEXTCLOUD_AUTH_TOKEN
              valueFrom:
                secretKeyRef:
                  name: nc-exporter-token
                  key: token
          resources:
            limits:
              memory: "128Mi"
              cpu: "250m"
          ports:
            - containerPort: 9205
              name: prom
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            privileged: false
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            runAsUser: 1000
            runAsGroup: 1000
      automountServiceAccountToken: false
  strategy: {}


