apiVersion: apps/v1
kind: Deployment
metadata:
  name: nc-exporter
  namespace: default
spec:
  selector:
    matchLabels:
      app: nc-exporter
  template:
    metadata:
      labels:
        app: nc-exporter
    spec:
      containers:
      - name: nc-exporter
        image: xperimental/nextcloud-exporter
        args:
          - "--server"
          - "https://cloud.{{domain_name}}"
        env:
        - name: NEXTCLOUD_AUTH_TOKEN
          valueFrom:
            secretKeyRef:
              name: nc-exporter-token
              key: token
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 9205
          name: prom


