apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: cloudflare-tunnel
resources:
  - tunnel-token.yaml
  - cludflared.yaml
  - ../../policies/allow-to-internet.yml
  - ../../policies/allow-to-dns.yml
  - ../../policies/allow-to-all-namespaces.yml
  - ../../policies/allow-to-nextcloud.yml
