apiVersion: v1
kind: Secret
metadata:
    name: authelia-db-secret
    namespace: security
type: Opaque
stringData:
    userPassword: ENC[AES256_GCM,data:k9Gy6WFmvCrQt3RBiXKCmx0erwfBRN5NFIE361qx/RUHwZdomhEfOg==,iv:olI0SXRJHFBpoGqMFhVsIeF43vMNSfDNbtbzOosVVZA=,tag:VPbQ8jqLpM55zvaeCPYtQQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2025-04-11T23:31:56Z"
    mac: ENC[AES256_GCM,data:1VpdgOSQ+9b8yptGz6X5qcW8F4NKyCN4TRQQ58T9xuH8J/Di05Vin4EpmZVxfJSddWG8vzezqWO3YxksEodNqu2qpt/qz1qgGVv8FiTE0kIdtuQqBlURScap7Y4K1FOQB/zTeK27ChtmrUCKbXswHBxdfeNZAisQVqlnkruNcyE=,iv:g+rbSXrc1w/MiRec9qYXJKQgOta/SzzHaTun1bHsszU=,tag:rMI+eZoootH3AbPZ8UeNHA==,type:str]
    pgp:
        - created_at: "2023-08-29T12:09:42Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA70fE7dz6LU0ARAAry6oK2zYVR4vuWPs6ZI5KZsqxqiOIRvYWlqlZRpnTgT9
            2Tt50q4XcObQghrxaVgSFQg6gX8XbCQm3d/MBsKfekMCVHF6DvXyk3zngxyety56
            +KBtTLJ2pZYnZQTkGZP2RwPcQlLviZBhwOxLf7Uv4dWajZMayNOu4e+YwmV9dPOU
            B65T+2lvEfNcNkoSRJ6khonXTblEAQqkuPlkspwgArmry4e98Ro/g8dvjwHxAIha
            ckMNdtxfppbzrH+z+HVWlMhfa84bX5A0CREWQNkvb8MZefk1O0WK9crujFwXBPO3
            z+EGSqgVkukgCL2FO0fJU8jc0/6a/rMsuGRJjz3jyNTNhpD+hWjWxIte5OqQepLh
            0IJWFZEJ5JVFGIv7mLJaX1s9aYJ0ahx/33yW5oWH68h6fc9UdFKRct61MQTzNy9M
            mvJ/Tn/4JgKICwV9HJiY029G9P1pjYL1Zo0D2Nzg106k8Pr9lXIUvH6Y0ZJtq8ay
            M6dQdveSDfvkKW0S3bJUsMB2bSosS62PS718HA0Xi5NEAhp1wSeXaf6ExIaeGEjY
            weOQuRIPJE8W/4T4+orr+JumXEK0+/jNsYSQzM8F4u74Tdyua0pIRTRG9AaW1OKt
            a+jpKiNM+fqISbdQoCOwtnq7jq9R9jxmkTGDgGvKnjIziaF55qqftTrKSLfIcTLS
            XgE+dTxu0y0roMvuztidB5LMbXL5kzx0QwLp5QdHIi+sp+6odKCNgRiARfqyL5Od
            Nfh9IMs7ywro+cwKF7m4oWbzCk0WEOyQnQl2WCokMMzAHRtGkvef/yYoIq7LdJo=
            =atPb
            -----END PGP MESSAGE-----
          fp: 1DF23F1E7AFCAB40F26B210123CFBB30193553AA
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
