# yaml-language-server: $schema=https://gist.githubusercontent.com/james-d-elliott/756de37a4398b3445072a60d674905c6/raw/ce90833b1ce145cb701184557dd964fa7546f19a/jsonschema.json
---
server:
  port: 80
session:
  domain: "${DOMAIN}"
  redis:
    host: redis.security.svc.cluster.local
    high_availability:
      sentinel_name: redis-master
      nodes:
        - host: redis-node-0.redis-headless.security.svc.cluster.local
          port: 26379
        - host: redis-node-1.redis-headless.security.svc.cluster.local
          port: 26379
        - host: redis-node-2.redis-headless.security.svc.cluster.local
          port: 26379

authentication_backend:
  password_reset:
    disable: true
  ldap:
    url: "ldaps://ipa.i.${DOMAIN}"
    tls:
      skip_verify: true
    username_attribute: uid
    additional_users_dn: cn=users,cn=accounts
    users_filter: (&({username_attribute}={input})(objectClass=person))
    additional_groups_dn: cn=groups,cn=accounts
    groups_filter: (&(member={dn})(objectclass=groupOfNames))

storage:
  postgres:
    host: postgresql.security.svc.cluster.local
    port: 5432
    database: authelia
    username: authelia
notifier:
  filesystem:
    filename: /dev/stdout
telemetry:
  metrics:
    enabled: true
    address: "tcp://0.0.0.0:8080"

access_control:
  default_policy: deny
  networks:
    - name: internal
      networks: ["10.0.0.0/8", "172.16.0.0/12", "192.168.0.0/16"]
  rules:
    - domain:
      - "*.i.${DOMAIN}"
      policy: one_factor
      subject: [["user:stefan"]]
    # - domain: ["grafana.devbu.io"]
    #   policy: bypass
    # - domain: ["letsblockit.devbu.io"]
    #   resources: ["^/lists.*$"]
    #   policy: bypass
    # - domain: ["navidrome.devbu.io"]
    #   resources: ["^/rest.*$"]
    #   policy: bypass
    # - domain: ["navidrome.devbu.io"]
    #   resources: ["^/metrics.*$"]
    #   policy: deny
    # - domain: ["wizarr.devbu.io"]
    #   resources: ["^/join.*$", "^/j/.*$", "^/setup.*$", "^/static/.*$"]
    #   policy: bypass
