# yaml-language-server: $schema=https://gist.githubusercontent.com/james-d-elliott/756de37a4398b3445072a60d674905c6/raw/ce90833b1ce145cb701184557dd964fa7546f19a/jsonschema.json
---
server:
  port: 80
session:
  domain: "${DOMAIN}"
  redis:
    host: redis.security.svc.cluster.local
    high_availability:
      sentinel_name: redis-master
      nodes:
        - host: redis-node-0.redis-headless.security.svc.cluster.local
          port: 26379
        - host: redis-node-1.redis-headless.security.svc.cluster.local
          port: 26379
        - host: redis-node-2.redis-headless.security.svc.cluster.local
          port: 26379

authentication_backend:
  password_reset:
    disable: true
  ldap:
    url: "ldaps://ipa.i.${DOMAIN}"
    tls:
      skip_verify: true
    username_attribute: uid
    additional_users_dn: cn=users,cn=accounts
    users_filter: (&({username_attribute}={input})(objectClass=person))
    additional_groups_dn: cn=groups,cn=accounts
    groups_filter: (&(member={dn})(objectclass=groupOfNames))

storage:
  mysql:
    host: cluster.db.svc.cluster.local
    port: 3306
    database: authelia
    username: authelia
notifier:
  smtp:
    host: mail.${DOMAIN}
    port: 587
    timeout: 5s
    # configured in secret
    # username: test
    # password: password
    sender: "Authelia <svc_authelia@${DOMAIN}>"
    identifier: auth.${DOMAIN}
    subject: "[Authelia] {title}"
    startup_check_address: svc_authelia@${DOMAIN}
    disable_require_tls: true
    disable_starttls: false
    disable_html_emails: false
telemetry:
  metrics:
    enabled: true
    address: "tcp://0.0.0.0:8080"

access_control:
  default_policy: deny
  networks:
    - name: internal
      networks: ["10.0.0.0/8", "172.16.0.0/12", "192.168.0.0/16"]
  rules:
    - domain:
      - "longhorn.k3s.i.${DOMAIN}"
      policy: two_factor
      subject: [["user:stefan"]]
    - domain:
      - "jellyseerr.docker1.i.${DOMAIN}"
      - "requests.${DOMAIN}"
      policy: one_factor
      subject: [["group:jellyfin_users"]]
    - domain:
        - "auth.${DOMAIN}"
        - "authelia.k3s.i.${DOMAIN}"
      policy: one_factor
      subject: [["group:jellyfin_users"]]
    - domain:
      - "*.i.${DOMAIN}"
      policy: one_factor
      subject: [["user:stefan"]]

identity_providers:
  oidc:
    cors:
      endpoints: ["authorization", "token", "revocation", "introspection"]
      allowed_origins_from_client_redirect_uris: true
    authorization_policies:
      jellyfin_users:
        default_policy: 'deny'
        rules:
          - policy: 'one_factor'
            subject: 'group:jellyfin_users'
    clients:
      - id: grafana
        description: Grafana
        secret: "${GRAFANA_OIDC_CLIENT_SECRET}"
        public: false
        authorization_policy: two_factor
        pre_configured_consent_duration: 1y
        scopes: ["openid", "profile", "groups", "email"]
        redirect_uris: ["https://grafana.${DOMAIN}/login/generic_oauth", "https://grafana.k3s.i.${DOMAIN}/login/generic_oauth"]
        userinfo_signing_algorithm: none
      - id: jellyseerr
        description: Jellyseerr
        secret: "${JELLYSEERR_OIDC_CLIENT_SECRET}"
        public: false
        audience: []
        authorization_policy: jellyfin_users
        pre_configured_consent_duration: 1y
        scopes: ["openid", "profile", "groups", "email"]
        redirect_uris: ["https://jellyseerr.docker1.i.${DOMAIN}/login/oidc/callback", "https://requests.${DOMAIN}/login/oidc/callback"]
        userinfo_signing_algorithm: none
        token_endpoint_auth_method: 'client_secret_post'
