---
# yaml-language-server: $schema=https://kubernetes-schemas.devbu.io/helmrelease_v2beta1.json
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app authelia
  namespace: security
spec:
  interval: 15m
  chart:
    spec:
      # renovate: registryUrl=https://bjw-s.github.io/helm-charts
      chart: app-template
      version: 1.3.2
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    initContainers:
      # 01-init-db:
      #   image: ghcr.io/onedr0p/postgres-initdb:14.7
      #   imagePullPolicy: IfNotPresent
      #   envFrom:
      #     - secretRef:
      #         name: authelia-secret
    controller:
      replicas: 1
      strategy: RollingUpdate
    image:
      repository: ghcr.io/authelia/authelia
      tag: 4.37.5
    args: ["--config", "/config/configuration.yml"]
    envFrom:
      - secretRef:
          name: authelia-secret
    enableServiceLinks: false
    service:
      main:
        ports:
          http:
            port: &port 80
          metrics:
            enabled: true
            port: 8080
    probes:
      liveness: &probes
        enabled: true
        custom: true
        spec:
          httpGet:
            path: /api/health
            port: *port
          initialDelaySeconds: 0
          periodSeconds: 10
          timeoutSeconds: 1
          failureThreshold: 3
      readiness: *probes
      startup:
        enabled: false
    serviceMonitor:
      main:
        enabled: true
        endpoints:
          - port: metrics
            scheme: http
            path: /metrics
            interval: 1m
            scrapeTimeout: 10s
    ingress:
      main:
        enabled: true
        ingressClassName: nginx
        annotations:
          nginx.ingress.kubernetes.io/configuration-snippet: |
            add_header Cache-Control "no-store";
            add_header Pragma "no-cache";
            add_header X-Frame-Options "SAMEORIGIN";
            add_header X-XSS-Protection "1; mode=block";
          hajimari.io/icon: mdi:shield-account
          cert-manager.io/issuer: freeipa-issuer
          cert-manager.io/issuer-group: certmanager.freeipa.org
          cert-manager.io/issuer-kind: ClusterIssuer
          cert-manager.io/common-name: authelia.k3s.i.${DOMAIN}
          nignx.ingress.kubernetes.io/force-ssl-redirect: "true"
        hosts:
          - host: &host authelia.k3s.i.${DOMAIN}
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - *host
            secretName: authelia-cert
    podSecurityContext:
      runAsUser: 568
      runAsGroup: 568
      fsGroup: 568
      fsGroupChangePolicy: OnRootMismatch
    persistence:
      config:
        enabled: true
        type: configMap
        name: authelia
        subPath: configuration.yml
        mountPath: /config/configuration.yml
        readOnly: true
      db:
        enabled: true
        type: emptyDir
        name: db
        mountPath: /db/
        readOnly: false
        shared:
          medium: "Memory"
    topologySpreadConstraints:
      - maxSkew: 1
        topologyKey: kubernetes.io/hostname
        whenUnsatisfiable: DoNotSchedule
        labelSelector:
          matchLabels:
            app.kubernetes.io/name: *app
    resources:
      requests:
        cpu: 5m
        memory: 10Mi
      limits:
        memory: 100Mi
