apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - helm-release.yml
  - secret.yml
configMapGenerator:
  - name: authelia
    namespace: security
    files:
      - "configuration.yml"
generatorOptions:
  disableNameSuffixHash: true
