apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: security
resources:
  - helm-release.yml
  - secret.yml
  - authelia-db-secret.yml
  - ../../../policies/allow-to-db.yml
configMapGenerator:
  - name: authelia
    namespace: security
    files:
      - "configuration.yml"
generatorOptions:
  disableNameSuffixHash: true
