apiVersion: v1
kind: Secret
metadata:
    name: authelia-secret
    namespace: security
type: Opaque
stringData:
    AUTHELIA_AUTHENTICATION_BACKEND_LDAP_PASSWORD: ENC[AES256_GCM,data:M/m5jkJNq8BsLXaONeKz1A55j5oYBd4F6MKz+OSr0nh0lE3TjCYSe1YbktI3jMfRTqg=,iv:MjuN+eZjNtgvwVJg6+Bk+XBS8t/B0zdDuyJU3mz7ti4=,tag:B71deFMrnk2OI+fHvrE/sw==,type:str]
    AUTHELIA_JWT_SECRET: ENC[AES256_GCM,data:BFzn8W8/e4gthY6ca7Maz3dd1tCwTtP7nnNr1sF5qGfkQ2ECjYwMueACwaU5U9eQrm29JR8xs/V6NEqj1+8dnqOg/ZfRKczQTP6VygsNET8=,iv:9u6++VjTT+kfahkLFCOswJqBLgVtoiCjhd12cPMfxB4=,tag:YyWHlT3nndLgvZNY5EBv3A==,type:str]
    AUTHELIA_SESSION_SECRET: ENC[AES256_GCM,data:n3ypI7sVd0l+o+cek5Vo0C8XGOARUJzV71aGMqalkO1hbxoIi45Wmt/UHqh9/Zz2qCTP4InjDD7Tp46Svb+SXN/vCxtERkAxhfiLiIWmMRw=,iv:8vk1q/hY5gnGuD/UEzfVR56CuauM60E1qPmr4dxvrBs=,tag:8PXIAlTHJX6AmKh6KIk2pA==,type:str]
    AUTHELIA_STORAGE_ENCRYPTION_KEY: ENC[AES256_GCM,data:8231ZRpDZIGtUUXnqfVJ5A6FJ0KJ88NYbxmwHcNzemE62UDPmCSOC0fJL1N1MpnFYxVuwPX5sDHpk8xg9FGJOk9c1h7pmXNtIdyZ9LN33mQ=,iv:iIXmOWh66SFKJxkZpd9dUPG/Yrf/jqglrm99fERMlRc=,tag:gqxPhbb4KUH5P1izJgts+w==,type:str]
    AUTHELIA_AUTHENTICATION_BACKEND_LDAP_BASE_DN: ENC[AES256_GCM,data:JGhNIoPia3B02aNyg3y1ehswi0I=,iv:YW1I+E0/rcQu+2kFJasBu0YGGmUsod9cjlFEgpgx32M=,tag:XkNsM5VMAu8WLaJgL0vMAg==,type:str]
    AUTHELIA_AUTHENTICATION_BACKEND_LDAP_USER: ENC[AES256_GCM,data:6Q1vS38Swuz9DOS4VG0DPgU/AeryLff13nvn+D02XXDDQ75l3a8f11XQuAqEpveMQX0MDdatwLGwyA==,iv:kUIkOjMvOE5QOpm3wbc58A3hW044JmCdjnbOBbI3chw=,tag:Jha7oyqTiz1Q8exFxPZVZQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2023-03-13T09:41:01Z"
    mac: ENC[AES256_GCM,data:rcAV7hJEROjKYyL+IeZRALf7NloS4pBe8S1y2vuMltU0eklbYyC3DQTarq/zOHYq5E7Gr8rh4Blq0H8hojV2ppvFLZGERuZlDxaeLLs+10NSrwPny186d7Lfy65BkS8/VpbaGdwlAe1Pi+RWsIAxIgdDFQt7jt9LC8QOdIFeiFs=,iv:k25+tSpHEt6PGD5zvzh6uCgTP2wPDAA4bWoSkHrseCI=,tag:829pEHmoQnXrl6GAX8IDjw==,type:str]
    pgp:
        - created_at: "2023-03-13T08:44:47Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA70fE7dz6LU0AQ/+MF8ufY3qMer0ED3yQI2HUoGDpPSR4HdN+abyo5cHUa2P
            Ta10ITyorWw2ywQd3Set4Bh3as9/UDNtRYcmV+6My7bwB0MwwVDCPDBlt4/kck9E
            0SJu/EewdzoXDCfWCpiemUrmVmtGVxr0U3eEYs/S+lNmShS4EQtcVLGr5Bca7c6y
            GPaPCxx8imo0QoHzuPy0mNvJVK/4vCzH11DIP5GwXfqPi7vp1E/pKgSmLxh9OWbE
            pF+kYpIMF8TKW/+WGkXkKb0iMz5NsZhcjGN8mNdz/p9C132fS3FgmwzsoQqmgvRN
            0VlET1Ksnxd1qmQFuiCY/yrR4vuViZvznSSRbBr4jrjsoXy2G2iTzGGNFAmjuzOE
            PGzqRpjqMd3FA6o8Nh52jnSnesePDFm51LoTAl85J5fANQzIk6rTO6xwhLZQ/im0
            KdF71POPdyXvVyprIidWNFwsKTuUUQhJDFWjuK591pQa2NPh7Y3dO8ODlHhmaEgG
            8rBLipmtotn4X/OnoTynpQ1TQPO+B78ZHjTQKJdGq2I1EDPWP8zZRrAKb0++3Yh1
            Vp+PotIzdFPi9nvHm6O5eU9qfT9hA2+dX/0erJaUd7bqS93Mk6Usl70d1YwWrnvl
            Zg/mmmGMAPeBATuutrV7+fLg881+IPuj8vY6crZ+cYJugPaZGZb27ZfGPd4Icz7S
            XAEskswkUKfLY9PxsVdI59Seng4bshjvokMrh7VWN6FMd5bopf4RlfWsbCzTOHEr
            fxf3yqWz0GdM5xSxUIlGyq1FfWOs+vm5QTpF3gRDNV/xVC0E63JNwyy2yf/V
            =abPL
            -----END PGP MESSAGE-----
          fp: 1DF23F1E7AFCAB40F26B210123CFBB30193553AA
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
