apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: blog
  namespace: websites
spec:
  imageRepositoryRef:
    name: blog
    namespace: websites
  filterTags:
    pattern: '^(?P<ts>\d{14})'
    extract: '$ts'
  policy:
    numerical:
      order: asc
