apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: blog
  namespace: websites
  annotations:
    cert-manager.io/issuer: freeipa-issuer
    cert-manager.io/issuer-group: certmanager.freeipa.org
    cert-manager.io/issuer-kind: ClusterIssuer
    cert-manager.io/common-name: blog.k3s.i.${DOMAIN}
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - blog.k3s.i.${DOMAIN}
    secretName: blog-cert
  rules:
  - host: blog.k3s.i.${DOMAIN}
    http:
      paths:
        - path: "/"
          pathType: Prefix
          backend:
            service:
              name: blog
              port:
                number: 8080
