- include: docker-ubuntu.yml
  when: ansible_distribution == "Ubuntu"
  become: yes

- include: docker-centos.yml
  when: ansible_distribution == "CentOS"
  become: yes
- name: create primary docker network
  docker_network:
    name: primary
  become: yes
