---
- hosts: linode0.i.stabl.one
  become: yes
  vars:
    replica: true
    replica_container_name: replica
    docker_dir: /var/docker
    freeipa_dir: "{{docker_dir}}/replica"
  vars_prompt:
    - name: ipa_admin_user_password
      prompt: "Please provide the password for user IPA ipa admin user"
      private: yes
  roles:
  - ../roles/common
  tasks:
    - name: create macvlan network
      docker_network:
        name: "macvlan"
        driver: macvlan
        driver_options:
          parent: tap0
        ipam_config:
          - subnet: "{{local_subnet}}"
            gateway: "{{local_subnet_gateway}}"

    - name: create replica directory
      file:
        path: "{{ freeipa_dir }}"
        state: directory


    - name: create options file
      file:
        path:  "{{ freeipa_dir }}/ipa-replica-install-options"
        state: touch

    - name: write options to file
      lineinfile:
        path: "{{ freeipa_dir }}/ipa-replica-install-options"
        line: "-U --no-ntp -d -P {{ipa_admin_user}} -w {{ipa_admin_user_password}} --skip-conncheck --no-ui-redirect --force-join --server ipa1.i.stabl.one --domain i.stabl.one"

    - name: start freeipa replica docker
      docker_container:
        name: replica
        image: "freeipa/freeipa-server:fedora-35-4.9.8"
        state: started
        detach: true
        recreate: no
        restart_policy: always
        hostname: "{{mailserver_replica_name}}"
        sysctls: "net.ipv6.conf.all.disable_ipv6=0"
        dns_servers: "{{ipa_server_ip}}"
        env:
          DEBUG_NO_EXIT: "1"
        networks:
          - name: primary
            ipv4_address: "172.18.0.17"
          - name: macvlan
            ipv4_address: "{{mailserver_replica_container_macvlan_ip}}"
        published_ports:
          - "127.0.0.1:443:443"
          - "127.0.0.1:53:53"
        volumes:
          - "/sys/fs/cgroup:/sys/fs/cgroup:ro"
          - "{{freeipa_dir}}:/data:Z"
        log_driver: json-file
        log_options:
          tag: "{% raw %}{{.ImageName}}|{{.Name}}|{{.ImageFullID}}|{{.FullID}}{% endraw %}"
        #command: "ipa-replica-install -U --no-ntp -P {{ipa_admin_user}} -w $(cat /password)"

    - name: Delete options file
      file:
        path: "{{ freeipa_dir }}/ipa-replica-install-options"
        state: absent
