---
- hosts:
  - k3s
  #serial: 1
  become: true
  gather_facts: true
  any_errors_fatal: true
  pre_tasks:
  - name: Set ansible_host fact
    set_fact:
      ansible_host: "{{ ansible_host | default(ansible_eth0.ipv4.address ,true)}}"
  - debug: var=ansible_host
  - name: Pausing for 5 seconds...
    pause:
      seconds: 5
  roles:
  - common
  - zsh
  - nfs_mount
  - k3s
  tasks:
  - name: Stop snapd
    systemd:
      state: stopped
      enabled: no
      name: snapd
  - name: Disable unattended upgrades for servers
    when: k3s_control_node
    lineinfile:
      path: /etc/apt/apt.conf.d/20auto-upgrades
      search_string: 'APT::Periodic::Unattended-Upgrade "1";'
      line: 'APT::Periodic::Unattended-Upgrade "0";'
  - name: Restart unattended upgrades systemd service
    systemd:
      state: restarted
      name: unattended-upgrades.service
