# yaml-language-server: $schema=https://raw.githubusercontent.com/ansible-community/schemas/main/f/ansible.json
---
- hosts: proxmox2.i.stabl.one
  vars_prompt:
    - name: ipa_admin_user_password
      prompt: Enter password for FreeIPA user
      private: yes
  vars:
    - ansible_become_pass: "{{ ipa_admin_user_password }}"
  become: true
  roles:
    - name: zfs_swap
    - name: network_watchdog
    - name: zfs_memory_limit
  tasks:
- hosts: proxmox1.i.stabl.one proxmox2.i.stabl.one
  vars_prompt:
    - name: ipa_admin_user_password
      prompt: Enter password for FreeIPA user
      private: yes
  vars:
    - ansible_become_pass: "{{ ipa_admin_user_password }}"
  become: true
  roles:
    - name: nfs_mount
      vars:
        nfs_mount:
          - src: 10.13.2.10:/DirStor
            dest: /DirStor
    - name: proxmox_intel_igpu
  tasks:
- hosts: proxmox
  tags:
    - cert
  vars_prompt:
    - name: ipa_admin_user_password
      prompt: Enter password for FreeIPA user
      private: yes
  vars:
    - ansible_become_pass: "{{ ipa_admin_user_password }}"
  roles:
    - proxmox_ipa_cert
- hosts: proxmox
  tags:
    - powersave
  vars_prompt:
    - name: ipa_admin_user_password
      prompt: Enter password for FreeIPA user
      private: yes
  vars:
    - ansible_become_pass: "{{ ipa_admin_user_password }}"
  roles:
    - powersave_governor
