version: '3'

tasks:
  jellyfin:
    cmds:
      - ansible-playbook  -i hosts --ask-vault-pass  jellyfin.yml
  mailserver:
    cmds:
      - ansible-playbook  -i hosts --ask-vault-pass  -K cloud/cloud.yml
