version: '3'

tasks:
  proxy:
    cmds:
      - ansible-playbook -i hosts --ask-vault-pass -K proxy.yml
  jellyfin:
    cmds:
      - ansible-playbook -i hosts --ask-vault-pass jellyfin.yml
  mailserver:
    cmds:
      - ansible-playbook -i hosts --ask-vault-pass -K cloud/cloud.yml
  cloud-replica:
    cmds:
      - ansible-playbook -i hosts --ask-vault-pass -K cloud/setup_replica.yml
  nextcloud:
    cmds:
      - ansible-playbook -i hosts --ask-vault-pass -K nextcloud.yml
  proxmox0:
    cmds:
      - ansible-playbook -i hosts --ask-vault-pass proxmox0.yml
  docker0:
    cmds:
      - ansible-playbook -i hosts --ask-vault-pass docker0.yml
  k3s:
    cmds:
      - ansible-playbook -i hosts --ask-vault-pass -K k3s.yml
