version: '3'

includes:
  cloud:
    taskfile: ./cloud
    dir: ./

tasks:
  proxy:
    cmds:
      - ansible-playbook -i hosts --ask-vault-pass -K proxy.yml
  jellyfin:
    cmds:
      - ansible-playbook -i hosts --ask-vault-pass jellyfin.yml
  mailserver:
    cmds:
      - ansible-playbook -i hosts --ask-vault-pass -K cloud/cloud.yml
  nextcloud:
    cmds:
      - ansible-playbook -i hosts --ask-vault-pass -K nextcloud.yml {{.CLI_ARGS}}
  proxmox0:
    cmds:
      - ansible-playbook -i hosts --ask-vault-pass proxmox0.yml {{.CLI_ARGS}}
  proxmox-servers:
    cmds:
      - ansible-playbook -i hosts --ask-vault-pass proxmox-servers.yml {{.CLI_ARGS}}
  docker1:
    cmds:
      - ansible-playbook -i hosts --ask-vault-pass docker1.yml
  k3s:
    cmds:
      - ansible-playbook -i hosts --ask-vault-pass -K k3s.yml
  ipa:
    cmds:
      - ansible-playbook -i hosts --ask-vault-pass ipa.yml
