
- name: Install aptitude using apt
  apt: name=aptitude state=latest update_cache=yes force_apt_get=yes
  become: yes
  become_method: sudo

- name: Install required system packages
  apt: name={{ item }} state=latest update_cache=yes
  loop: [ 'apt-transport-https', 'ca-certificates', 'curl', 'software-properties-common', 'python3-pip', 'virtualenv', 'python3-setuptools']

- name: Add Docker GPG apt Key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present
  become: yes
  become_method: sudo

- name: Add Docker Repository
  apt_repository:
    repo: deb https://download.docker.com/linux/ubuntu focal stable
    state: present
  become: yes
  become_method: sudo

- name: Update apt and install docker-ce
  apt: update_cache=yes name=docker-ce state=latest
  become: yes
  become_method: sudo

- name: Make sure old docker module is absent
  pip:
    name:
      - docker-py
    state: absent
  become: yes
  become_method: sudo

- name: Install Docker Module for Python
  pip:
    name:
      - docker
  become: yes
  become_method: sudo
