- name: Add repository
  yum_repository:
   name: docker
   description: Docker Repo
   baseurl: https://download.docker.com/linux/centos/7/x86_64/stable/
   gpgkey: https://download.docker.com/linux/centos/gpg
  become: true
  become_method: sudo

  #become: true
- name: install docker install Docker packages
  dnf:
    name:
     - docker-ce
     - docker-ce-cli
     - containerd.io
    state: latest
  become: true
  become_method: sudo

- name: install docker packages using commandline
  command: dnf install -4 -q -y --nobest docker-ce docker-ce-cli containerd.io
  become: true
  become_method: sudo

- name: Start docker
  systemd:
    state: started
    name: docker
  become: true
  become_method: sudo
