apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: bitnami-redis
  namespace: security
spec:
  interval: 10m
  url: oci://registry-1.docker.io/bitnamicharts/redis
  ref:
    tag: 21.2.5
