---
# yaml-language-server: $schema=https://kubernetes-schemas.devbu.io/helmrelease_v2beta1.json
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: redis
  namespace: security
spec:
  interval: 15m
  chart:
    spec:
      # renovate: registryUrl=https://charts.bitnami.com/bitnami
      chart: redis
      version: 18.5.0
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
  maxHistory: 3
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    auth:
      enabled: false
      sentinel: false
    master:
      persistence:
        enabled: false
    replica:
      replicaCount: 1
      persistence:
        enabled: false
    sentinel:
      enabled: true
      masterSet: redis-master
      getMasterTimeout: 10
      startupProbe:
        failureThreshold: 2
      persistence:
        enabled: false
    metrics:
      enabled: true
      serviceMonitor:
        enabled: true
