kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: allow-scraping
  namespace: media
spec:
  policyTypes:
  - Ingress
  podSelector: {}
  egress:
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app: jellyfin-exporter
