global:
scrape_configs:
  - job_name: unifi-poller
    scrape_interval: 30s
    static_configs:
    - targets: ['unifi-poller.default.svc.cluster.local:9130']
  - job_name: 'prometheus'
    scrape_interval: 15s
    static_configs:
      - targets: ['localhost:9090']