apiVersion: v1
kind: Secret
metadata:
    namespace: freeipa-issuer-system
    name: freeipa-auth
stringData:
    user: ENC[AES256_GCM,data:SlQr4hxiHA==,iv:Ke7IjCTxr9Mmyga0tGDGCa94uOLx1zDSzM7sfwIWTSs=,tag:YfwWXxIl0mPCoehs8Ez7mQ==,type:str]
    password: ENC[AES256_GCM,data:im/Zmy/WqoXWmKD5P0qmEUDUsGfiWg3onqn4bxKNr92kjuNC7440JpBklcJ5djrI0U0=,iv:WwSKsVlQZGLCESRMR4ponzQbKJZT1mOUorNLb8w1uGs=,tag:b7srwWKlAcOPPrwzZYVo0g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-07-07T11:13:33Z"
    mac: ENC[AES256_GCM,data:T0SjlhVHf3WYjId7MPOxc3vcYkcdlrt2EuQhwW+JNvqzt4qpjeH7DOpIPLhoA08dVG1DP8p36ZViSP4RcMMedltU+jQWB6mvuXwfsgKhsmL6mepYouroR63hMPSQsQuLjs2N0czJJtb6JbBS/mfg11MvNO/NLr+8/ukK/RYb3rM=,iv:4I+29BP/TYd6Z2y93h5KhpZ8E+Q5S1jRpFjGCKi9W08=,tag:kDce/O50ncp1R3xOmK17gQ==,type:str]
    pgp:
        - created_at: "2022-07-07T11:13:32Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA70fE7dz6LU0AQ//RIeewnU/7eOdX4HGrR0sza9qOZCZs8aoIJ2aGvZysp67
            nESRxXSTCn/bwlXIDCKybPkYEoUNOy2Q+N9zxRkVDsgxi7SlPtL++De6i2+VyR0B
            9z1soC2ExKB1vL/V1e2bJKZSwDT/gc1saVfekzwbz7AxFjlSHj60UTar3VPlq7o4
            /dB3nFypDnhZyn+XYNqlXU4Gj8vK2fA6ke9KVLvIQZ97nf2egZ/jNmba4U2O0KxV
            wxoHpoqtRj+JcE0A9+bDculB7Q/LJennAgm1xvJXkK6i7T+kovkAd2U3BNU6TJ/y
            evmuoO4d7JM1SD5j5+xL7aO7GCrKj8n+HDwef2GPJZz03pygypUrXadOlx1tG/Xb
            WdNEvJ3LZOLu+nFDoHK1g25hw1DujAC3WqlRJFw0+LIIusFgI5WyAa3ZC1HsKiiT
            qgNJk/fMte4tjdCdFPa6Isgso7MBDqy+ESC4/nWyg9tHOtZiHsDbxqHI7ttVipi7
            3Ash146FIT+ue3uGiOyHyuw4+qrXmrWEQ5Wi693kHshfZUmSFT3k3p1pcaWuhPSR
            q6iGGdx5PE4Ab8+2NEx6Kc1N8MzCrPZA5Zo5hHantoziKx1n6iq9oIHL9di7ymvx
            z5jjq/s3vVPUh+TdjDP8HlE096+TAzTU5L14yUwlq9LiAcmh3MSQeHQdXGwsk6LS
            XgGSCG0cDfDxlKz94j0pH5MvJjpDAT+dDJim9f6izettojzWwNs30z0CH0SSQmm9
            M6ERwOAxvBbkXhRqVBtWg2vZNi/uOD7/9xcL1WKYFEFGXZahZVWfI7g6uYSdJLI=
            =03Ua
            -----END PGP MESSAGE-----
          fp: 1DF23F1E7AFCAB40F26B210123CFBB30193553AA
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
