apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - helm-release.yml
  - https://github.com/StefanAbl/freeipa-issuer/config/default
  - freeipa-user-secret.yml
  - cluster-issuer.yml
