# https://pve.proxmox.com/pve-docs/pve-admin-guide.html#sysadmin_zfs_limit_memory_usage
- name: Write ZFS ARC memory limit (4GiB)
  notify: handlers
  lineinfile:
    state: present
    create: true
    path: /etc/modprobe.d/zfs.conf
    line: options zfs zfs_arc_max=4294967296
