apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: prometheus-blackbox-exporter
  namespace: monitoring
spec:
  interval: 15m
  timeout: 15m
  chart:
    spec:
      # renovate: registryUrl=https://prometheus-community.github.io/helm-charts
      chart: prometheus-blackbox-exporter
      version: 11.4.1
      sourceRef:
        kind: HelmRepository
        name: prometheus-community-charts
        namespace: flux-system
      interval: 15m
  values:
    extraVolumes:
      - name: ca-certs
        hostPath:
          path: /etc/ssl/certs/ca-certificates.crt
          type: File
    extraVolumeMounts:
      - name: ca-certs
        mountPath: /etc/ssl/certs/ca-certificates.crt
        readOnly: true
    config:
      modules:
        http_2xx:
          prober: http
          timeout: 5s
          http:
            valid_http_versions: ["HTTP/1.1", "HTTP/2.0"]
            follow_redirects: true
            preferred_ip_protocol: "ip4"
        unifi:
          prober: http
          timeout: 5s
          http:
            follow_redirects: true
            preferred_ip_protocol: "ip4"
            fail_if_body_not_matches_regexp:
            - "UniFi Network"
