apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: prometheus-blackbox-exporter
  namespace: monitoring
spec:
  interval: 15m
  timeout: 15m
  chart:
    spec:
      # renovate: registryUrl=https://prometheus-community.github.io/helm-charts
      chart: prometheus-blackbox-exporter
      version: 8.17.0
      sourceRef:
        kind: HelmRepository
        name: prometheus-community-charts
        namespace: flux-system
      interval: 15m
  values:
    extraVolumes:
      - name: ca-certs
        hostPath:
          path: /etc/ssl/certs/ca-certificates.crt
          type: File
    extraVolumeMounts:
      - name: ca-certs
        mountPath: /etc/ssl/certs/ca-certificates.crt
        readOnly: true
