apiVersion: apps/v1
kind: Deployment
metadata:
  name: keel-exporter
  namespace: default
  annotations:
    keel.sh/policy: "major"
    keel.sh/trigger: poll     # enable active repository checking
    keel.sh/approvals: "1"    # required approvals to update
spec:
  selector:
    matchLabels:
      app: keel-exporter
  template:
    metadata:
      labels:
        app: keel-exporter
      annotations:
        container.apparmor.security.beta.kubernetes.io/keel-exporter: runtime/default
        seccomp.security.alpha.kubernetes.io/pod: runtime/default
    spec:
      containers:
        - name: keel-exporter
          image: ghcr.io/stefanabl/keel-exporter:v0.0.2
          env:
            - name: KEEL_URL
              valueFrom:
                secretKeyRef:
                  name: keel-exporter
                  key: url
            - name: KEEL_USER
              valueFrom:
                secretKeyRef:
                  name: keel-exporter
                  key: user
            - name: KEEL_PASS
              valueFrom:
                secretKeyRef:
                  name: keel-exporter
                  key: pass
          resources:
            limits:
              memory: "128Mi"
              cpu: "250m"
          ports:
            - containerPort: 8080
              name: prom
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            privileged: false
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            runAsUser: 1000
            runAsGroup: 1000
      automountServiceAccountToken: false
  strategy: {}
