- debug: var=ansible_facts.hostname
- debug: var=ansible_facts.fqdn
- name: Ensure certificate directory exists
  become: yes
  file:
    state: directory
    path: /etc/ssl/pve-ipa/

- name: Check if the certificate file exists
  stat:
    path: "/etc/ssl/pve-ipa//pveproxy-ssl.pem"
  register: stat_result

- name: check if certificate exists
  become: yes
  when: stat_result.stat.exists
  changed_when: false
  failed_when: status_result != 0 and "No request found that matched arguments." not in status_result.stdout
  shell:
    cmd: ipa-getcert status -f /etc/ssl/pve-ipa//pveproxy-ssl.pem
  register: status_result

- name: Add service to FreeIPA
  ipa_service:
    name: "HTTP/{{ ansible_facts.fqdn }}"
    state: present
    ipa_host: "{{ ipa_server }}"
    ipa_user: "{{ ipa_admin_user }}"
    ipa_pass: "{{ ipa_admin_user_password }}"
    hosts: "{{ ansible_facts.fqdn }}"

- name: Request Certificate from IPA
  become: yes
  when: not stat_result.stat.exists and ( status_result.rc is defined and not status_result.rc == 0 )
  register: certificate_request_result
  shell:
    cmd: >-
      ipa-getcert request -r
      -f pveproxy-ssl.pem
      -k pveproxy-ssl.key
      -N CN="{{ ansible_facts.fqdn }}"
      -K "HTTP/{{ ansible_facts.fqdn }}@{{ internal_domain|upper }}"
      -C "pvenode cert set /etc/ssl/pve-ipa/pveproxy-ssl.pem /etc/ssl/pve-ipa/pveproxy-ssl.key --force --restart"
    chdir: "/etc/ssl/pve-ipa/"
