apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: db
resources:
  - name.yaml
  - mariadb-operator
  - ../../policies/allow-from-ingress.yml
  - ../../policies/allow-to-dns.yml
  - ../../policies/allow-to-internet.yml
  - ../../policies/allow-to-ipa-dns.yml
