apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: db
resources:
  - galera
  - name.yaml
  - ../../policies/allow-to-dns.yml
  - ../../policies/allow-to-ipa-dns.yml
  - ../../policies/allow-to-kube-control.yml
  - ../../policies/allow-to-internet.yml
  - ../../policies/allow-to-s3.yml
  - allow-to-db-ns.yml
