
- file:
    path: "{{item}}"
    state: directory
    owner: "{{mailserver_bindUser}}"
    group: "{{mailserver_bindUser}}"
    mode: 0700
  with_items:
    - "{{docker_dir}}/backup/"

- name: template minio config
  template:
    src: "{{item}}"
    dest: "{{docker_dir}}/backup/"
    owner: "{{mailserver_bindUser}}"
    group: "{{mailserver_bindUser}}"
    mode: 0600
  with_items:
    - config.json

- docker_container:
    name: backup
    image: minio/mc
    state: started
    detach: true
    recreate: true
    restart_policy: always
    command: mirror --watch /data local/mail-backup/
    networks:
      - name: primary
    volumes:
      - "{{docker_dir}}/backup/config.json:/root/.mc/config.json:ro"
      - "/etc/ipa/ca.crt:/etc/ipa/ca.crt:ro"
      - "{{docker_dir}}/mail:/data:ro"
    dns_servers: "{{ipa_server_ip}}"
    log_driver: json-file
    log_options:
      tag: "{% raw %}{{.ImageName}}|{{.Name}}|{{.ImageFullID}}|{{.FullID}}{% endraw %}"
